### ISSUE TITLE
PlotMe Permission Problem

### ISSUE THREAD

**Issue by SuperAthleteRox** [WorldCretornica/PlotMe-Core#100]
For some reason, I am unable to set a plot limit to a particular group. For my server's default group, I have added the permission 'plotme.limit.1' but users of the default group can still claim more than 1 plot. I have looked everywhere for help, but there is not a hint of help anywhere.
I am using Bukkit, PlotMe (obviously) and PermissionsEx as my permissions plugin.

Thanks for the help in advance! I really want to get this server on the road.

Btw, PlotMe is an excellent plugin, best plots plugin available!!

**Comment by MarkusAV** [comment]
In your plotme configuration files, is the plotworld in all lowercase letters?
It could also help reinstalling PlotMe

**Comment by SuperAthleteRox** [comment]
No, it isn't, I actually renamed the world to 'Creative' to make it easier for me. I will try reinstalling, thank you so much for the help!

**Comment by MarkusAV** [comment]
Make it all lowercase in the configuration :)
