### ISSUE TITLE
Mods block generation 

### ISSUE THREAD

**Issue by LucienAclantis** [WorldCretornica/PlotMe-Core#102]
I use mods and plugins at the same time so it's like a cauldron serveur and i generate it with multiverse:

/mv create {NAME} normal -g PlotMe-DefaultGenerator

the generation dont applicate. is there a solution to this problem? is there a way to force the generation with plugins?
ps: the plugins works fine without mods, i use the modpack : resonant rise

**Comment by MarkusAV** [comment]
Are you saying that everything works fine when you run a server without mods?

**Comment by MattBDev** [comment]
Cauldron is no longer supported due to the DMCA takedown and the project is no longer maintained. I have heard that some biome mod breaks support but I will not fix this.
