### ISSUE TITLE
Plot sell - price does not display

### ISSUE THREAD

**Issue by SBPrime** [WorldCretornica/PlotMe-Core#105]
When doing __plot sell__ or __plot sell  \<price\>__ the price is no where visible.

**Comment by MattBDev** [comment]
Where is it not visible? On the sign or in chat after executing the command?

**Comment by SBPrime** [comment]
On the signs. After executing the command a new sign is added to the plot and the border changes and that's all. The player receives a proper message in chat.

**Comment by MattBDev** [comment]
That is a cause of me being stupid. Thanks for letting me know.
