### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by SaDb0y** [WorldCretornica/PlotMe-Core#107]
Hi.
I am getting errors after upgrading.
Here is a log when executing /p setowner 
http://pastebin.com/UtBwBdJk
And when executing /p home it says I don't have any plot, while when I try to /p info on my plot it says the owner is me, it's like all the plots owners were deleted but they aren't.
The datebase isn't deleted though.

I did all the instruction for upgrading from v13 to v15.2 perfectly, the world name is in lowercase in all configs and folders, the generator has been set to PlotMe-DefaultGenerator.

**Comment by SaDb0y** [comment]
My spigot build is 1649, the 1.7/1.8 protocol.
WorldEdit is updated too.

Did I do a mistake by upgrading it cause v15.2 is for 1.8 only?

**Comment by MattBDev** [comment]
yes

**Comment by SaDb0y** [comment]
So is it safe to downgrade it?
And how?

**Comment by MattBDev** [comment]
Yes it is safe.
No it is not compatible with worldedit 6.
