### ISSUE TITLE
PlotSquared Converter

### ISSUE THREAD

**Issue by MacMeBenny** [WorldCretornica/PlotMe-Core#108]
This plugin is horrible which I converted too and I'm wondering if there's a way to convert back?

**Comment by EvilOlaf** [comment]
The best way to convert back from any change is to use the backup which you created before.

**Comment by MacMeBenny** [comment]
So there is no way to currently convert PlotsSquared to PlotMe?

**Comment by MattBDev** [comment]
No but I feel like I should make a conversion method

**Comment by MacMeBenny** [comment]
That would be awesome honestly lol - this other plugin is horrible.

**Comment by MacMeBenny** [comment]
I know I'm not top priority but would there be an estimated time of
completion for the converter?

**Comment by MattBDev** [comment]
@MacMeBenny Depends on how many bugs get fixed. By February most likely.

**Comment by MattBDev** [comment]
Moved to WorlCretornica/LegacyConverter
