### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by srut2000** [WorldCretornica/PlotMe-Core#109]
I can get plotme to spawn a world but when you get into the world it is just a normal biome.
I was wondering is it because i have the Biomes'OPlenty mod on the server at the same time?

**Comment by MattBDev** [comment]
Yes.

**Comment by srut2000** [comment]
So how do i get it working

**Comment by MarkusAV** [comment]
Remove the Biome'OPlenty plugin or get a per-world-plugin plugin
