### ISSUE TITLE
Per-world claim permissions

### ISSUE THREAD

**Issue by MegaNarwhal** [WorldCretornica/PlotMe-Core#110]
Using PlotMe 0.15.2, PermissionsEx 1.23.1. I'm trying to add a second plot world restricted only to users above a certain rank. I negated the `plotme.use.claim` and `plotme.use.auto` permissions in that world for ranks that should not be able to claim and only granted them to the ranks I wish to be able to claim in it. However, lower ranks are still able to obtain a plot in the world by using `/plotme auto` from the other creative world that they **are** allowed to claim in. A permission like `plotme.denyclaim.<world>` would be very useful and save me from having to set up a separate server for the second plot world.

**Comment by MattBDev** [comment]
you should be able to stop this by setting allowWorldTeleport to false.
