### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by RobbinTH** [WorldCretornica/PlotMe-Core#114]
Hey guys,

I have a problem with plotme. I'm running the newest version, i just clicked the download button. 
So, the problem is:
If i typ /plotme it says /plotme back, and i cant do any command. I have al the permissions and i'm op.
Can someone tell me what did i wrong ?
Sorry for bad English, i'm dutch ;-)

RobbinTH

**Comment by MarkusAV** [comment]
Hi Robbin, when you installed plotme, did you only drag over the PlotMe-Core.jar? You need to have the PlotMe-DefaultGenrrator as well! If this doesn't fix your issue, check your console log for any errors. You also want to make sure that:
* Plotworld names are in lowercase in the configs
* Your server is in online mode
* Using worldedit 6.x
* Highly recommended: Spigot 1.8
