### ISSUE TITLE
Error PlotMe Limits not functioning

### ISSUE THREAD

**Issue by Lumindor** [WorldCretornica/PlotMe-Core#115]
Hey there,
Was testing PlotMe on Spigot 1.8, I have given the permission node plotme.limit.2 to the player permissions.
However when they claim in the world they are able to keep claiming and the Limit doesn't change or limits the player from claiming more than 2 plots.

Screenshot: http://i.imgur.com/1YeGmXg.png

**Comment by MattBDev** [comment]
I am looking into this right now.

**Comment by MattBDev** [comment]
Cannot Reproduce

**Comment by EvilOlaf** [comment]
As seen there is still a plot limit of 0 and you claimed already two.
Therefore it seems were operator or had any permission that overrides the limit.
Check your permission setup.
