### ISSUE TITLE
Economy broken (again)?

### ISSUE THREAD

**Issue by EvilOlaf** [WorldCretornica/PlotMe-Core#116]
Spigot 1.8
Vault 1.5.2
iConomy 7
PlotMe 0.15.2

Plot buy does not subtract the price from players funds.

Actually not my own bug, had two independent users in IRC with the same problem.

**Comment by MattBDev** [comment]
Invalid but will be left open for one more day for investigation

**Comment by EvilOlaf** [comment]
Honestly I can not reproduce the "invalid" tag.
Anyway it seems that this configuration does not work for some users.
I had myself the same configuration and can't reproduce.

**Comment by MattBDev** [comment]
If it doesn't work then it has to be a Spigot/Bukkit issue because I am implementing Vault exactly as described in the VaultAPI.

**Comment by EvilOlaf** [comment]
The only think it MAY could be is that spigot changed something.
I had an older build from later 2014 for testing PlotMe/Vault/iConomy.

However it might be interesting to investigate a bit further if another concerned users reports here. If it is indeed related to Spigot or Vault I am pretty sure they were glad to get a previewed and detailled issue report about ;).
