### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by MastefChief** [WorldCretornica/PlotMe-Core#117]
Every time i try to make a plot world i keep getting an error.

Screenshots:
http://prntscr.com/5vsnts

**Comment by MattBDev** [comment]
This does not provide much detail. Does your world "Plots" exist in both config files? Make sure "Plots" is in lowercase letters when specified in the config's.

**Comment by EvilOlaf** [comment]
Little Offtopic: How about a simple "HowTo report issues" and FAQ for the most common errors?

**Comment by MarkusAV** [comment]
@EvilOlaf It's not possible to do with github issues, however I will work on a faq page at the wiki soon

**Comment by EvilOlaf** [comment]
I don't think thats a problem. Just create your FAQ, "most common errors" and "how to report an issue" page and then change the link of "ask question/get support" at Spigot resource to it. After the hint to "read this page carefully before opening an issue report" you may link them to git.
You also should add a hint to be patient in IRC and wait for answer.

**Comment by MarkusAV** [comment]
@EvilOlaf Website is still under development. My goal for the site is to make it as friendly and easy as possible

**Comment by EvilOlaf** [comment]
*like*
