### ISSUE TITLE
World will not Generate

### ISSUE THREAD

**Issue by tyipie** [WorldCretornica/PlotMe-Core#119]
I do the command: /mv create plotworld normal -g PlotMe-DefaultGenerator, but when I TP to that world (/mv tp plotworld) It's just a regular world? I've searched all over youtube, tried a thousand different methods, I also tried multiworld with no luck.

**Comment by EvilOlaf** [comment]
Make sure that PlotMe-DefaultGenerator has been loaded successful on server startup and check the worlds.yml of multiverse. Ensure your plotworld uses PlotMe-DefaultGenerator as world generator.

**Comment by tyipie** [comment]
I checked all that, its all working. I tried redownloading plotme, now it works but says this is not a plotworld. the config says the world name is plotworld, and that is what I named the world..

**Comment by EvilOlaf** [comment]
Did you use lowercase for your world only?
For further investigation you may paste your worlds.yml, PlotMe config and PlotMe-DefaultGenerator config on pastebin and put the links here.

**Comment by tyipie** [comment]
http://pastebin.com/qCwEBV43 thats the plotme config, I coukdnt find worlds.yml on the FTP. Heres the Plotme-Defaultgenerator config... http://pastebin.com/Qtdb93na

**Comment by EvilOlaf** [comment]
Look for it in the MultiVerse directory.

**Comment by tyipie** [comment]
Alright, here it is. http://pastebin.com/S0nYaJiv

**Comment by Schtooping** [comment]
Just got to  /plugins/Muiltverse-Core and look for the worlds.yml. At the bottom  of the config add the line     generator: PlotMe-DefaultGenerator  

Save the file and restart the server.   It will now work

**Comment by ZachBora** [comment]
@tyipie
* In the root folder of the server, edit bukkit.yml and add at the end
```
worlds:
  plotworld:
    generator: PlotMe-DefaultGenerator
```

* Stop the whole server.
* In server root, folder plotworld, go in the region subfolder and delete all region files.
* Start server

**Comment by tyipie** [comment]
That worked, thanks ZachBora. Thank everyone else for helping also!
