### ISSUE TITLE
Can't generate plotme world

### ISSUE THREAD

**Issue by Schtooping** [WorldCretornica/PlotMe-Core#120]
I have used plotme for years so I'm fairly certain I have everything set right but for some reason when I try and generate a plotme world no plots generate. It's just a normal world I'm pasting my config files here:

Plotme config.yml 
http://pastebin.com/aByQTzT4

PlotMe-DefaultGenerator
http://pastebin.com/GbRWaveL

My startup log:
http://pastebin.com/QGizAGUy

Any help would be greatly appreciated. I have been banging my head up against the wall over this for days. I have used this plugin for a long time but just can't get it to function properly.

Thanks so much

**Comment by EvilOlaf** [comment]
Make sure you use PlotMe-DefaultGenerator as world generator in your worlds.yml of MultiVerse.

**Comment by Schtooping** [comment]
So I have seen others say this but it's not clear to me where to put this info as it doesn't exist as a setting on the worlds.yml. Do I add a line at the bottom? Even the documentation on the multiverse 2 github isn't clear about it. I think these instructions make a lot of assumptions about what people know. I have no problem editing configs as long as i  know I'm not gonna mess stuff up. Sorry to be a bother with this..

**Comment by Schtooping** [comment]
Okay I figured it out. Thanks for the help. It seems to be working fine now
