### ISSUE TITLE
Another problem once plotme world is generated

### ISSUE THREAD

**Issue by Schtooping** [WorldCretornica/PlotMe-Core#121]
Getting an error when trying to run any plotme command. Paste bin below. Any ideas what the problem might be?

http://pastebin.com/X6LYjXM6

**Comment by EvilOlaf** [comment]
Do a restart and it should work well.

**Comment by Schtooping** [comment]
Well of course it's that simple.. Sorry to bother you again

**Comment by EvilOlaf** [comment]
No problem ;)
