### ISSUE TITLE
WorldEdit Doesnt work on plots

### ISSUE THREAD

**Issue by EnriMarte** [WorldCretornica/PlotMe-Core#125]
why world edit doesnt work on plots, its anyway to do it work on plots? thanks you

**Comment by MarkusAV** [comment]
You need to use WorldEdit Anywhere if you are worldediting outside your own plots; activivate and use at own risk using /plotme weanywhere

**Comment by MattBDev** [comment]
If you want to use world edit on your own plots you need to give players worldedit permissions and be using worldedit 6. To use worldedit outside of plots, you must enable worldedit anywhere.

This issue will be marked as closed if there is no response within 2 days.

**Comment by EnriMarte** [comment]
i am the owner and i want to use the worldedit on anothes plots i mean to help them

**Comment by MattBDev** [comment]
Then you just do /plotme weanywhere
If this issue is solved, please let me know so I can close this issue.

**Comment by EnriMarte** [comment]
yes!!! thanks you very much. i have another problem now LOL. the /plotme home doesnt have tp time i want to edit them and cant find on the config file. help me pls

**Comment by ZachBora** [comment]
Please create a new issue for the plotme home, it's not an option to put time at the moment.
