### ISSUE TITLE
Add optional timer to teleport to plot's

### ISSUE THREAD

**Issue by EnriMarte** [WorldCretornica/PlotMe-Core#129]
the /plotme home doesnt have tp time i want to edit them

**Comment by EvilOlaf** [comment]
tp time?

**Comment by EnriMarte** [comment]
yes

**Comment by MattBDev** [comment]
What the heck is tp time? You mean a delay to teleport? You can do this with other plugins.

**Comment by EnriMarte** [comment]
how?

**Comment by MattBDev** [comment]
I meant to reopen this.

**Comment by EnriMarte** [comment]
so? no ones knows?

**Comment by EnriMarte** [comment]
help?

**Comment by MattBDev** [comment]
Fixed and will be in 0.17
