### ISSUE TITLE
/plotme auto error

### ISSUE THREAD

**Issue by EnriMarte** [WorldCretornica/PlotMe-Core#130]
why when users want to put /plotme auto they get this message: " No plot found within 3 plots, contact an admin" i go like on the empy plots i put /plotme auto and still get same message helpme pls

**Comment by EvilOlaf** [comment]
Did you change the plot auto settings in your config?

**Comment by EnriMarte** [comment]
yes

**Comment by MattBDev** [comment]
Then that is why you are getting this issue. If you stand on top of a plot and do /plotme auto it doesn't do much if you changed the plot auto value. If you stand on top of the plot you need to do /plotme claim.

Issue closed.

**Comment by EnriMarte** [comment]
LOL so people have to walk into their own plots?

**Comment by MattBDev** [comment]
What did you change the plot auto value to?

**Comment by EnriMarte** [comment]
already fix it thanks you

**Comment by ZachBora** [comment]
@EnriMarte the plot auto limit isn't per player, there's a permission node for max plots per player.
The plot auto command is used to automatically claim a new plot, nearest available one. The plot auto limit config is to prevent an infinite loop when it's looking for new plots. So for example if it's set to 10,000 then the plot auto command will stop at something like 5000x 5000z plot ids. But it should find a plot before then. We could probably remove that config, I've never seen the plot auto cause issues aside from when people missuse the config.
