### ISSUE TITLE
Can't /plot remove <name> | Also, people with multiple plots can't /p h or build on it

### ISSUE THREAD

**Issue by YepImRobbie** [WorldCretornica/PlotMe-Core#132]
28.01 14:04:23 [Server] INFO ... 14 more
28.01 14:04:23 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-fa7cbf9-42ebec1]
28.01 14:04:23 [Server] INFO at com.worldcretornica.plotme_core.bukkit.BukkitCommand.onCommand(BukkitCommand.java:166) ~[?:?]
28.01 14:04:23 [Server] INFO at com.worldcretornica.plotme_core.commands.CmdRemove.exec(CmdRemove.java:33) ~[?:?]
28.01 14:04:23 [Server] INFO Caused by: java.lang.NullPointerException
28.01 14:04:23 [Server] INFO at java.lang.Thread.run(Thread.java:744) [?:1.7.0_55]
28.01 14:04:23 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-fa7cbf9-42ebec1]
28.01 14:04:23 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-fa7cbf9-42ebec1]
28.01 14:04:23 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-fa7cbf9-42ebec1]
28.01 14:04:23 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot.jar:git-Spigot-fa7cbf9-42ebec1]
28.01 14:04:23 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_55]
28.01 14:04:23 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_55]
28.01 14:04:23 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-fa7cbf9-42ebec1]
28.01 14:04:23 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-Spigot-fa7cbf9-42ebec1]
28.01 14:04:23 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-fa7cbf9-42ebec1]
28.01 14:04:23 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot.jar:git-Spigot-fa7cbf9-42ebec1]
28.01 14:04:23 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot.jar:git-Spigot-fa7cbf9-42ebec1]
28.01 14:04:23 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:git-Spigot-fa7cbf9-42ebec1]
28.01 14:04:23 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-fa7cbf9-42ebec1]
28.01 14:04:23 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-fa7cbf9-42ebec1]
28.01 14:04:23 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'plot' in plugin PlotMe v0.15.2
28.01 14:04:23 [Server] ERROR null

**Comment by MattBDev** [comment]
Please resubmit with a more detailed report in markdown format instead of posting just an error. I cannot help you with just a snippit of an error log. Markdown format can be found using this link: https://guides.github.com/features/mastering-markdown/
