### ISSUE TITLE
Projectiles

### ISSUE THREAD

**Issue by YepImRobbie** [WorldCretornica/PlotMe-Core#133]
Hello, projectiles such as Egg and Snowballs, don't affect players or mobs, this is an issue since the plugin CrackShot uses snowballs as a projectile for guns, and thus, they're completely ineffective in the plotworld.

I'm certain it's down to PlotMe since they work in non-plotme worlds.

How do I allow snowballs and eggs to have an effect so Crackshot isn't useless. Thanks.

**Comment by YepImRobbie** [comment]
Additionally, mobs aren't damaging players.

All of this worked before updating to the core.

**Comment by ZachBora** [comment]
Yeah... someone was complaining about egg so we had disabled them. We will see if we can make configuration for what is disabled, that should resolved your problem.

**Comment by MarkusAV** [comment]
I like that ideea Zach :+1:

**Comment by MattBDev** [comment]
This has been added for 0.16
Closing issue.

**Comment by YepImRobbie** [comment]
Was this completed in 0.16 it didn't say on the Bukkit update logs regarding the jar.

**Comment by MattBDev** [comment]
It was completed. I suggest not downloading the plugin from BukkitDev as they don't really have a good plugin publishing platform. Try downloading it from spigot instead
