### ISSUE TITLE
Better way to reset plots

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [WorldCretornica/PlotMe-Core#135]
A smarter way to reset plots would be to require WorldEdit & AsyncWorldEdit IF a config setting is set to true like:
_lag-free-plot-resetting: true_

Then use the (upcoming) api: https://github.com/SBPrime/AsyncWorldEdit/issues/29

**Comment by MattBDev** [comment]
We already have async plot clearing in the next version. We don't need to use worldedit or asyncworledit for it.

**Comment by TheOnlyRealTGS** [comment]
Oh, great!
