### ISSUE TITLE
/plotme auto Problem

### ISSUE THREAD

**Issue by stuart99** [WorldCretornica/PlotMe-Core#136]
Hello,

Recently i have added PlotMe To my server. I have set the world up and have done the config but when i went to do /plotme auto it disconnected me with a internal error. I have never had this error before and was wondering if you could help me out. Here is a screenshot of the console http://prntscr.com/609jwr.
Please get back to me as soon as possible.

Thanks.

-Stuart

**Comment by EvilOlaf** [comment]
Seems like this is not related to plotme, more to chatcontrol...

**Comment by stuart99** [comment]
DO you know how i can fix it?

**Comment by EvilOlaf** [comment]
Try disabling chatcontrol and try again.

**Comment by stuart99** [comment]
Ok

**Comment by stuart99** [comment]
Ok so i took The ChatControl plugin out of my server and it still gets this error http://prntscr.com/60a5ci.

**Comment by EvilOlaf** [comment]
Your version of plotme is outdated. Therefore it will not receive any further support. Get the current version here: http://www.spigotmc.org/resources/plotme.2131/

**Comment by stuart99** [comment]
Ok Thank you

**Comment by stuart99** [comment]
Ok So i got the new plotme plugins and installed them and got this error when doing the same command http://prntscr.com/60am86

**Comment by stuart99** [comment]
So i installed the new plotme plugins and got this error when doing the same command http://prntscr.com/60am86.

**Comment by MattBDev** [comment]
You did not setup plotme correctly. Please follow the upgrade guide on the PlotMe website. Issue closed.
