### ISSUE TITLE
when i generate a world it is a normal world

### ISSUE THREAD

**Issue by raceking37** [WorldCretornica/PlotMe-Core#137]
i did /mv create plotworld normal -g PlotMe
i also get time out and when i rejoin 
and type /mv tp plotworld 
it is a normal world

**Comment by EvilOlaf** [comment]
console output?

**Comment by ZachBora** [comment]
it's /mv create plotworld normal -g PlotMe-DefaultGenerator

**Comment by raceking37** [comment]
still does not work
http://pastebin.com/W32TBKaZ

**Comment by EvilOlaf** [comment]
```
[17:52:43 INFO]: Could not set generator for world 'plotworld': Plugin 'PlotMe-DefaultGenerator' does not exist[m
```
Make sure that PlotMe-DefaultGenerator is loaded properly at server start.

**Comment by raceking37** [comment]
how do i do that

**Comment by raceking37** [comment]
i works !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
i forgot to put the plugin back in
thanks

**Comment by MarkusAV** [comment]
If you encountering more problems, try adding this line to the bottom of your bukkit.yml file
```
worlds:
  plotworld:
    generator: PlotMe-DefaultGenerator
```
