### ISSUE TITLE
plotme multiverse not completing world creation

### ISSUE THREAD

**Issue by wickstim** [WorldCretornica/PlotMe-Core#139]
Hi,
I am using a Bungeecord setup (bungeecord  has ip forward set to true and have bungeecord set to true in spigot.yml).
Have had plots running well for 18 months.  Upgraded to 0.15.2 - followed instructions - deleted old plugin, add new plugin and default-generator etc
when I use multiverse to create a plots world, using the command /mv create plotsworld NORMAL -g PlotMe-DefaultGenerator I get a failed message.
A folder is made for the new world with a folder and file in it, but it is not complete.  Image attached.

**Comment by MattBDev** [comment]
there is no image attached. if you are not using the latest version of bukkit or spigot then i suggest upgrading. The bungeecord information is irrelevant. Please resubmit this issue or discuss it in the spigot forums where help is more likely to be found.
