### ISSUE TITLE
Console error spammed: Could not pass event PlayerInteractEvent to PlotMe v0.15.2

### ISSUE THREAD

**Issue by MuroHasegawa** [WorldCretornica/PlotMe-Core#141]
Getting this error spammed in console, not to sure if it's cause of some other plugins I may have or what.

http://pastebin.com/HBby2vbq

**Comment by ZachBora** [comment]
This will be fixed in the next version.

**Comment by MuroHasegawa** [comment]
Cool, till then I'll stick with 0.13f

**Comment by ZachBora** [comment]
@MuroHasegawa if you have time, you could test using version from our CI http://ci.worldcretornica.com/

**Comment by MuroHasegawa** [comment]
There is no console spam with your build #27 PlotMe-Core and build #6 of PlotMe-DefaultGenerator. But now creeper and tnt explosions aren't blocked.

**Comment by ZachBora** [comment]
Verify in your config file for a setting to disable those. I know @MattBDev was working on the events, I am not sure what he has done with those.

**Comment by ZachBora** [comment]
P.S. @MattBDev I don't know if it's an issue introduces or a config, but if it's a config it should be prevent these by default.

**Comment by MuroHasegawa** [comment]
Both "DisableExplosion" & "DisableIgnition" are set to true in my config.

**Comment by ZachBora** [comment]
@MuroHasegawa can you give us your server log? This shouldn't happen.

**Comment by MuroHasegawa** [comment]
Here is the latest log from my server. 
https://www.mediafire.com/?6sedfloxwt364l1

**Comment by MattBDev** [comment]
The first issue I see is that you are using an extremely old version of worldedit that doesn't work with plotme.

**Comment by MattBDev** [comment]
The second issue is the captions file didn't change to captions.yml

**Comment by MattBDev** [comment]
Third, looks like worldguard has tnt enabled in some places.

**Comment by MuroHasegawa** [comment]
Newest update for worldedit doesn't like our server but I'm trying to fix that. I already have a captions.yml inside of the PlotMe folder. As for WorldGuard, I've added all the flags to fix the explosions.
