### ISSUE TITLE
Name should be updated upon join

### ISSUE THREAD

**Issue by ItsHarry** [WorldCretornica/PlotMe-Core#142]
If a player changes their name, the name should be updated in the database upon join.

**Comment by Maescool** [comment]
+1

**Comment by ZachBora** [comment]
I thought it already did that, must have forgotten it.

**Comment by ItsHarry** [comment]
There is a method you made in SqlManager called convertPlotToNewUUID() or something like that, but it is never called.

**Comment by MattBDev** [comment]
@ItsHarry nice catch :+1:

**Comment by ZachBora** [comment]
where is this convertPlotToNewUUID?

**Comment by ZachBora** [comment]
or is it updatePlotsNewUUID

**Comment by MattBDev** [comment]
It's updatePlotsNewUUID()

**Comment by ItsHarry** [comment]
Thanks for the quick help guys by the way.

**Comment by ItsHarry** [comment]
When do you think you will get this finished?

**Comment by ItsHarry** [comment]
Nevermind, I see that it has been fixed in the latest commit. Thanks

**Comment by MattBDev** [comment]
@ItsHarry have you tested it yet? If you can test it and prove this is all fixed and every command is working and such, it would be extremely helpful

**Comment by MrNut** [comment]
@MattBDev I'm currently using the dev version, it all looks good to me! Great work.

**Comment by MattBDev** [comment]
Commands are working and such?

**Comment by MrNut** [comment]
Yeah, looks fine to me. I'll report back when my playerbase reports back :)

**Comment by MattBDev** [comment]
thank you. My IRC is also open on my computer and will be all day. I won't be able to respond but I will see any message you leave me.

**Comment by ItsHarry** [comment]
Is there a Jenkins server? For some reason I get an IncompatibleClassChangeError after compiling it myself..

```java
[16:36:33 ERROR]: Error occurred while enabling PlotMe v0.16-SNAPSHOT (Is it up
to date?)
java.lang.IncompatibleClassChangeError: class com.worldcretornica.plotme_core.bukkit.BukkitServerBridge has interface com.worldcretornica.plotme_core.api.IServerBridge as super class
```

**Comment by MattBDev** [comment]
ci.worldcretornica.com

**Comment by MattBDev** [comment]
I have seen this more than once. I am not sure how It is an Incompatible class change since it completely is compatible and implements all the methods in the interface.

**Comment by ItsHarry** [comment]
I don't get it either lol, it's an abstract class so I don't understand how the compiler changed it to an interface..

**Comment by ItsHarry** [comment]
Seems to be working well, beside the NPE in PlayerInteractEvent which I have made a pull request for.
