### ISSUE TITLE
Upgrading problems

### ISSUE THREAD

**Issue by PrisonHeist** [WorldCretornica/PlotMe-Core#146]
Hi, I recently updated my version of PlotMe to the one including PlotMe-DefaultGenerator, I've done as instructed in the upgrade guide by editing my bukkit.yml to say the generator is -DefaultGenerator and not just 'PlotMe'. Also removed the old plugin.

Now when the server starts up it starts to do UUID database conversion which is fine, however when I teleport to someones plot the coordinates aren't aligned with where the plot is, i.e part of the path is someones plot, a corner of someone elses plot is still part of someone elses, etc..

Also in the config files for PlotMe and PlotMe-DefaultGenerator it seems to create a new plotworld configuration for a world "plots". My actual plotworld is called "Plots"(capital P), however it seems to duplicate this configuration every time it is removed from the config.

Any ideas how this can be sorted or is this a known bug (being worked on?).

Thanks.

**Comment by MarkusAV** [comment]
Your PlotMe world must be lowercased in the configurations

**Comment by MattBDev** [comment]
also check to make sure your configs are the same settings you previously had. It is a known issue that the plot size may change sometimes. It is a random chance but it does happen.

**Comment by MattBDev** [comment]
Fixed in 0.16

**Comment by PrisonHeist** [comment]
I get this in console:
[20:58:13 INFO]: [PlotMe] Finished fetching 5011 UUIDs. Starting database update
.
[20:58:13 WARN]: [PlotMe] Name not found at mojang : hinsky1992, removing.
[20:58:13 WARN]: [PlotMe] Name not found at mojang : mvporder69, removing.
[20:58:13 WARN]: [PlotMe] Name not found at mojang : flashfox49, removing.
[20:58:13 WARN]: [PlotMe] Name not found at mojang : so_cal_badass, removing.
[20:58:13 ERROR]: [PlotMe] Conversion to UUID failed :
[20:58:13 ERROR]: [PlotMe] [SQLITE_CONSTRAINT]  Abort due to constraint violatio
n (columns idX, idZ, world, player are not unique)
[20:58:13 ERROR]: [PlotMe]   org.sqlite.DB.newSQLException(DB.java:383)
[20:58:13 ERROR]: [PlotMe]   org.sqlite.DB.newSQLException(DB.java:387)
[20:58:13 ERROR]: [PlotMe]   org.sqlite.DB.execute(DB.java:342)
[20:58:13 ERROR]: [PlotMe]   org.sqlite.DB.executeUpdate(DB.java:363)
[20:58:13 ERROR]: [PlotMe]   org.sqlite.PrepStmt.executeUpdate(PrepStmt.java:85)

[20:58:13 ERROR]: [PlotMe]   com.worldcretornica.plotme_core.SqlManager$2.run(Sq
lManager.java:1869)
[20:58:13 ERROR]: [PlotMe]   org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.
run(CraftTask.java:71)
[20:58:13 ERROR]: [PlotMe]   org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsync
Task.run(CraftAsyncTask.java:53)
[20:58:13 ERROR]: [PlotMe]   java.util.concurrent.ThreadPoolExecutor.runWorker(U
nknown Source)
[20:58:13 ERROR]: [PlotMe]   java.util.concurrent.ThreadPoolExecutor$Worker.run(
Unknown Source)
[20:58:13 ERROR]: [PlotMe]   java.lang.Thread.run(Unknown Source)

**Comment by PrisonHeist** [comment]
Here is what my PlotMe config file looked like before update:

worlds:
  Plots:
    PlotAutoLimit: 1000
    PathWidth: 7
    PlotSize: 30
    BottomBlockId: '7'
    WallBlockId: '44'
    PlotFloorBlockId: '2'
    PlotFillingBlockId: '3'
    RoadMainBlockId: '112'
    RoadStripeBlockId: '155'
    RoadHeight: 64
    DaysToExpiration: 5000
    ProtectedBlocks:
    - 54
    - 61
    - 62
    - 120
    - 94
    - 93
    - 84
    - 25
    - 355
    - 118
    - 117
    - 138
    - 140
    - 145
    - 143
    - 146
    - 116
    - 130
    - 77
    - 69
    - 330
    - 23
    - 158
    - 154
    - 330
    - 96
    - 70
    - 389
    PreventedItems:
    - '351:15'
    - '259'
    - '328'
    - '343'
    - '342'
    - '407'
    - '333'
    ProtectedWallBlockId: '44:7'
    ForSaleWallBlockId: '44:1'
    AuctionWallBlockId: '44:1'
    AutoLinkPlots: true
    DisableExplosion: true
    DisableIgnition: true
    economy:
      UseEconomy: false
      CanPutOnSale: false
      CanSellToBank: false
      RefundClaimPriceOnReset: false
      RefundClaimPriceOnSetOwner: false
      ClaimPrice: 0.0
      ClearPrice: 0.0
      AddPlayerPrice: 0.0
      DenyPlayerPrice: 0.0
      RemovePlayerPrice: 0.0
      UndenyPlayerPrice: 0.0
      PlotHomePrice: 0.0
      CanCustomizeSellPrice: false
      SellToPlayerPrice: 0.0
      SellToBankPrice: 0.0
      BuyFromBankPrice: 0.0
      AddCommentPrice: 0.0
      BiomeChangePrice: 0.0
      ProtectPrice: 0.0
      DisposePrice: 0.0
usemySQL: false
mySQLconn: jdbc:mysql://localhost:3306/minecraft
mySQLuname: root
mySQLpass: password
globalUseEconomy: false
AdvancedLogging: true
Language: english
allowWorldTeleport: true
defaultWEAnywhere: true
auto-update: false
allowToDeny: true

**Comment by PrisonHeist** [comment]
Here's a video on what is happening:
https://www.youtube.com/watch?v=eLs-pbLBQeM&feature=youtu.be

**Comment by ZachBora** [comment]
@PrisonHeist I understand this issue, someone had a friend on his plot. This friend changed name. Upon server start that friend didn't have access anymore so he readded that person to his plot.

But then the converter tried to replace the old name for the new name and it did the violation. I will add a check to not re-add existing names.

**Comment by PrisonHeist** [comment]
I have kept the server offline since the name change update so no one has been online to readd anyone to a plot
