### ISSUE TITLE
Border Does Not Change Back

### ISSUE THREAD

**Issue by Taleson** [WorldCretornica/PlotMe-Core#151]
The border does not reset to marble after unclaiming a plot. It is not an invalid report, for the feller who cannot reproduce, it is a valid problem with the plugin. Fix it because it shouldn't happen. Also, probs a good thing you can't reproduce because you are retarded. :P

**Comment by MattBDev** [comment]
I am the developer and the one who closed the issue. I closed it was an issue several commits ago but it is fixed now. If you are calling me retarded then you are being very offensive not just to me but to people with an actual disability. Please do not resubmit this.
