### ISSUE TITLE
Open chests in other people's plots

### ISSUE THREAD

**Issue by ItsHarry** [WorldCretornica/PlotMe-Core#153]
Hey,

My players are complaining that it's possible to open chests in other people's plots. I don't whether this was always possible, or that it broke in the latest update.

Thanks

**Comment by ZachBora** [comment]
Hi harry,

Check in config if chest is protected block (that's 54 for chest and 146 for trapped chest)

**Comment by ItsHarry** [comment]
Yes, it's in there, but players are still able to open chests. This problem was not there in 0.15.2

**Comment by ZachBora** [comment]
I see, must be something we broke... damn. @MattBDev first that has time check into this issue.

**Comment by MattBDev** [comment]
I am not sure what caused it to break because all the code for it is the same.

**Comment by ItsHarry** [comment]
Why do I see this in the plugin.yml?

```java
    plotme.unblock.*:
      default: true
      description: Unblocks a certain item that was blocked in the config
```
