### ISSUE TITLE
Upgrading problems #2

### ISSUE THREAD

**Issue by PrisonHeist** [WorldCretornica/PlotMe-Core#157]
This is a follow up to Upgrading problems: https://github.com/WorldCretornica/PlotMe-Core/issues/146

After upgrading to the latest PlotMe there are problems with the coordinates of the plot, see video: https://www.youtube.com/watch?v=eLs-pbLBQeM&feature=youtu.be

This was my PlotMe configuration BEFORE updating:
worlds:
Plots:
PlotAutoLimit: 1000
PathWidth: 7
PlotSize: 30
BottomBlockId: '7'
WallBlockId: '44'
PlotFloorBlockId: '2'
PlotFillingBlockId: '3'
RoadMainBlockId: '112'
RoadStripeBlockId: '155'
RoadHeight: 64
DaysToExpiration: 5000
ProtectedBlocks:
- 54
- 61
- 62
- 120
- 94
- 93
- 84
- 25
- 355
- 118
- 117
- 138
- 140
- 145
- 143
- 146
- 116
- 130
- 77
- 69
- 330
- 23
- 158
- 154
- 330
- 96
- 70
- 389
PreventedItems:
- '351:15'
- '259'
- '328'
- '343'
- '342'
- '407'
- '333'
ProtectedWallBlockId: '44:7'
ForSaleWallBlockId: '44:1'
AuctionWallBlockId: '44:1'
AutoLinkPlots: true
DisableExplosion: true
DisableIgnition: true
economy:
UseEconomy: false
CanPutOnSale: false
CanSellToBank: false
RefundClaimPriceOnReset: false
RefundClaimPriceOnSetOwner: false
ClaimPrice: 0.0
ClearPrice: 0.0
AddPlayerPrice: 0.0
DenyPlayerPrice: 0.0
RemovePlayerPrice: 0.0
UndenyPlayerPrice: 0.0
PlotHomePrice: 0.0
CanCustomizeSellPrice: false
SellToPlayerPrice: 0.0
SellToBankPrice: 0.0
BuyFromBankPrice: 0.0
AddCommentPrice: 0.0
BiomeChangePrice: 0.0
ProtectPrice: 0.0
DisposePrice: 0.0
usemySQL: false
mySQLconn: jdbc:mysql://localhost:3306/minecraft
mySQLuname: root
mySQLpass: password
globalUseEconomy: false
AdvancedLogging: true
Language: english
allowWorldTeleport: true
defaultWEAnywhere: true
auto-update: false
allowToDeny: true

**Comment by PrisonHeist** [comment]
I may have over 1000 plots, could it be that I need to change the PlotAutoLimit in old config before running the server for first time with new version of PlotMe?

**Comment by EvilOlaf** [comment]
I don't think so because the PlotAutoLimit value means that if a user uses /plot auto and after 1000 tries the system could not find a free plot it will respond to the user to ask an admin for a free plot.

**Comment by MattBDev** [comment]
@evilolaf is correct

**Comment by MattBDev** [comment]
You need to make sure all your configs are normal. Be aware there are two config files now.

**Comment by PrisonHeist** [comment]
I haven't touched the config i just let plotme do the conversion

**Comment by MattBDev** [comment]
Not smart. check all your settings. there was a known bug in 0.15 that sometimes reset the plot size

**Comment by MattBDev** [comment]
I'm going to assume you fixed this?

**Comment by PrisonHeist** [comment]
I'm not sure yet, I updated to your latest build the one which tells you when you enter plots and since then I get UUID conversion failure messages in console. When I do /plotme auto it gives me a plot which was previously owned by someone else so not sure if this is due to database errors. I'm awaiting a status update on https://github.com/WorldCretornica/PlotMe-Core/issues/156

**Comment by PrisonHeist** [comment]
This is resolved.
