### ISSUE TITLE
Owner signs don't update

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [WorldCretornica/PlotMe-Core#161]
Title explains the issue

**Comment by MattBDev** [comment]
Fixed for 0.16.3 in this commit 8d613eea9337051f3c4f44378cb31f28a2227d43

**Comment by TheOnlyRealTGS** [comment]
What events trigger this? I tried to place/break blocks, and marking/unmarking the plot as done, it doesn't update.

**Comment by MattBDev** [comment]
it actually wasn't fixed since there was a bug with the attempted fix. Thanks for updating this. i'll reopen

**Comment by MattBDev** [comment]
I am deploying a fix for 0.17 :smile:

**Comment by MattBDev** [comment]
Fixed
