### ISSUE TITLE
defaultWEAnywhere problem

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [WorldCretornica/PlotMe-Core#162]
I have defaultWEAnywhere: true and have to do /plot weanywhere everytime I login in order to actually be able to use WE anywhere

**Comment by MattBDev** [comment]
Do you have the plotme.admin.weanywhere permission?

**Comment by TheOnlyRealTGS** [comment]
I'm op

**Comment by TheOnlyRealTGS** [comment]
I'm op

**Comment by MattBDev** [comment]
Fixed in commit 8d613eea9337051f3c4f44378cb31f28a2227d43
