### ISSUE TITLE
/p auto and "now entering ## plot"

### ISSUE THREAD

**Issue by PrisonHeist** [WorldCretornica/PlotMe-Core#164]
Sorry for continuous tickets just two more things,
When doing /p auto it gives me a plot which was previously owned by someone else, it doesn't give the next available plot like for example I did /p auto and it gave me -16;-7 which had some blocks already on it and I have many plots.

Is there a way I can make it so it starts selecting new plots from the last plot ID?

Also, can you add it so that the "Now entering ##'s plot" only happens for those with the permission node for it as I don't want everyone getting spammed by it, also is it possible to have it so that it says it just once not every step taken - if not no worries.

**Comment by jomo** [comment]
afaik `/p auto` searches for the next unclaimed plot in some radius, I think there are plans to switch to a "more logical" approach by selecting the next free plot starting at `0;0`.

**Comment by MattBDev** [comment]
1. You are running a development build that is unsupported. Why are you not running 0.16.3?
2. don't combine two reports into 1 issue
3. If plot auto gives you a plot that is claimed then you have a deeper issue to investigate. either your world settings are corrupt and you should fix them or the database is corrupt. You can check the example configs on the website.
