### ISSUE TITLE
/p Auto major lag

### ISSUE THREAD

**Issue by big2002monkey** [WorldCretornica/PlotMe-Core#167]
Whenever someone uses /p auto it lags the server. There are no server logs other than the server crashing (Someone types /p auto: In Console it just comes up with our plugin "Server not responding for # seconds")

**Comment by EvilOlaf** [comment]
Do you have any crash logs in your main server directory?
looking something like hs_err_pid12258.log

**Comment by big2002monkey** [comment]
Yes. We do, would you like me to put it in a pastebin/something of that sort?

**Comment by MarkusAV** [comment]
Pastebin or hastebin

**Comment by ItsHarry** [comment]
Same issue with all versions of 0.16.x. Server freezes for over 30 seconds every time somebody types /p auto

**Comment by big2002monkey** [comment]
http://pastebin.com/h4z1fqXx

**Comment by MattBDev** [comment]
I'll make this an aysnc task and see if that will improve things.

**Comment by MattBDev** [comment]
Can any of you test this by modifying the plot auto limit to 50?

**Comment by MattBDev** [comment]
This will also require a rewrite of SQLManager

**Comment by ItsHarry** [comment]
I currently have plot limit set to 300, which gives this message: "No plot found"

When I set it 1000, that's when the command caused lag, so I changed it back to 300.

**Comment by ItsHarry** [comment]
@MattBDev @ZachBora 
What do you think of what I did here? Mainly, the exists() method I created in SqlManager. 
https://github.com/ItsHarry/PlotMe-Core/commit/00cc9bb4b363f7c440b79cd2ce5b887dce90607e

**Comment by ItsHarry** [comment]
Anything I can help with to speed up the process to 0.17? /plot auto is still disabled on my server and I would love to have it back again

**Comment by MattBDev** [comment]
I need to talk to think of death about some changes which will allow me to do other things and make sure this works without a problem.

**Comment by ItsHarry** [comment]
Btw, may I ask how you are going to optimize the /plot auto command?

I kind of got tired of waiting, so I tried implementing a caching system that looks for empty plots in a background task, which seems to work quite nicely. It basically always has 10 plots cached, so that /plot auto is pretty much instantaneous, and since the task runs asynchronously, it doesn't lag the server.

**Comment by MattBDev** [comment]
@ItsHarry I am paring this task up with #180 to work on caching all plots to memory. The result will be less calls to the database and all plot auto command calls need to have a seperate thread for searching.

**Comment by ItsHarry** [comment]
Alright, that should also work. Hopefully it won't use up too much memory.

**Comment by MattBDev** [comment]
@ItsHarry Memory usage is all based on the number of plots you have. The more you have, the more memory is used.
