### ISSUE TITLE
World Generation stopped

### ISSUE THREAD

**Issue by hasezoey** [WorldCretornica/PlotMe-Core#169]
I have a bug for the Team!: (No Plots more!!!)
![javaw 2015-02-08 19-37-20-07](https://cloud.githubusercontent.com/assets/10911626/6097770/fa4838b6-afc9-11e4-92cf-8667495f56dd.jpg)
![javaw 2015-02-08 19-37-17-89](https://cloud.githubusercontent.com/assets/10911626/6097769/fa47ddee-afc9-11e4-9918-0fc3405ed7f6.jpg)
![javaw 2015-02-08 19-37-19-08](https://cloud.githubusercontent.com/assets/10911626/6097771/fa4a55ec-afc9-11e4-9ae3-43882cfa26d8.jpg)

The Website: https://minecraft.nitrado.net/map/128.65.221.205/#/205/64/555/-4/0/0

**Comment by hasezoey** [comment]
Please HELP!

**Comment by MattBDev** [comment]
Are your generators all set properly? Did you accidently reload the server? If world generation stops for no reason then it isn't a plotme issue.

**Comment by hasezoey** [comment]
Did you accidently reload the server: I have the plotworld to the head world made and I have Reloadet. the plots must be first /p claim and then are /p reset. only the ways are just not there anymore!
(Sorry for my bad English: I have https://translate.google.de took :D) thanks (I have a new world createt)
