### ISSUE TITLE
Remove /p as alias please

### ISSUE THREAD

**Issue by FuRiouSOne** [WorldCretornica/PlotMe-Core#170]
Please remove p as an alias as it interferes with /p for mcMMO party chat toggle. I have disabled it in the plugin/yml file but will be annoying having to do this every time i need to update plotme having to manually adjust your plugin.yml within the jar before updating.

Thanks.

**Comment by jomo** [comment]
[no](http://wiki.bukkit.org/Commands.yml)

**Comment by FuRiouSOne** [comment]
@jomo i have tried adjusting the commands alias within bukkit commands file but it doesn't fix the /p for mcMMO party chat toggle. Only way to allow mcMMO party chat to toggle correctly is disabling p as alias within plotme manually or you guys removing it as it was before. plot alias for plotme was just fine, no need to interfere with another plugins alias....

**Comment by big2002monkey** [comment]
Many people use /p instead of Plot.
No way are they removing it for one person...

**Comment by MattBDev** [comment]
No way we are removing it. You can remove it yourself by modifying the plugin.yml in PlotMeCore.jar

**Comment by FuRiouSOne** [comment]
So for 2 years or so you didnt have it (everyone was fine with using /plot [command]) you now decide to screw over mcMMO users by adding it? Interesting concept, thanks.

**Comment by MarkusAV** [comment]
@FuRiouSOne Acctually you have two options;
Either modify the PlotMe-Core's "plugin.yml" and delete the "p" command
OR
modify your "commands.yml" file to make the "p" command alias to whatever command you need it to be, more info here: http://wiki.bukkit.org/Commands.yml

**Comment by MattBDev** [comment]
PlotMe has had /p for awhile. it is nothing new.
