### ISSUE TITLE
Plot Limits per world

### ISSUE THREAD

**Issue by MattBDev** [WorldCretornica/PlotMe-Core#172]
plotme.limit.<world>.# should possibly be the config for it.
FInd a way to handle this if only one plotworld exists.

**Comment by jomo** [comment]
shouldn't that be handled by the permission plugin? Most of these allow you to define per-world permissions.

**Comment by MattBDev** [comment]
Do permissions plugins allow them to do per world permissions? If so then this really isn't needed.

**Comment by MarkusAV** [comment]
PermissionsEx allows for per-world permissions.., I know that GroupManager(globalgroups.yml) doesn't but not sure about others..
But it wouldn't matter, because PlotMe would still recognize the amount of plots a player have.

This is a needed feature :)

**Comment by MattBDev** [comment]
I don't know about offering support for this. Because some players don't care for instructions and like to do whatever they want, I can't count on someone following the format @MarkusAV is suggesting. Permissions plugins should really have per world permissions.
GroupManager is a plugin that won't be receiving features for bukkit except for compatibility whenever a new version of Bukkit is released so that is the exception. I consider that DEAD.

**Comment by MattBDev** [comment]
Are there any plugins that do not allow for per world permissions? I don't want plotme to contain a permission management system just for this one feature. If most plugins except for group manager don't allow for per world permissions then I will add this.

**Comment by MattBDev** [comment]
I have been overthinking this. I know how to make this work.

**Comment by MattBDev** [comment]
Fixed in 0.17 . There can only be one limit set but the limit can be reached in one world without being reached in another.
