### ISSUE TITLE
...Invalid report?

### ISSUE THREAD

**Issue by KingDonut** [WorldCretornica/PlotMe-Core#173]
So basically, on **** creative, I changed my minecraft ign to KingDonut, before, it was tomthesailor2002. I now have no permissions what so ever, so is anyone able to get it back to me? I had 2 plots (owner:tomthesailor2002) and 1 plot (owner:KingDonut) and I will be very happy if I culd get them back! Thanks!

**Comment by EvilOlaf** [comment]
Do you run your server in offline mode?

**Comment by KingDonut** [comment]
no I dont think so...

**Comment by MattBDev** [comment]
1) What Minecraft version is the server running.
2) Are you the server owner? If not, I can't help you
3) Are you saying that you have no permissions anymore or that you do just don't own a plot anymore?

**Comment by jomo** [comment]
4) Which version of PlotMe are you running?

**Comment by MarkusAV** [comment]
5) Do you like potatoes?
Please try to explain your issue better, right now it looks like this is a problem with your permissions

**Comment by MattBDev** [comment]
Closed because the reporter decided to not follow up.
