### ISSUE TITLE
You can push blocks out of your plot using pistons

### ISSUE THREAD

**Issue by ItsHarry** [WorldCretornica/PlotMe-Core#177]
It's possible to push blocks into other plots by using pistons
![2015-02-09_21 28 45](https://cloud.githubusercontent.com/assets/914835/6125424/23f541c0-b116-11e4-8bce-6b119332ae7d.png)

**Comment by ItsHarry** [comment]
Nevermind, I tested it myself and I couldn't reproduce it.

**Comment by jomo** [comment]
IIRC you cab push blocks **into** plots, but not out.

**Comment by ItsHarry** [comment]
How does that happen though? You would have to push the blocks from a neighboring plot

**Comment by jomo** [comment]
It can't happen unless someone (i.e. admin) places them on the road

**Comment by ItsHarry** [comment]
Yeah exactly, that's why I'm closing this =)
