### ISSUE TITLE
Item frames aren't protected by plot settings in plot world.

### ISSUE THREAD

**Issue by TWSSYesterday** [WorldCretornica/PlotMe-Core#178]
http://pastebin.com/pvt1tw0a Current PlotMe config
Version: 0.17 Snapshot - http://ci.worldcretornica.com/job/PlotMe-Core/76/

**Comment by MattBDev** [comment]
What version of Bukkit/Spigot?

**Comment by TWSSYesterday** [comment]
http://gyazo.com/2ba1227c49aba66248d88b1c31f62fe6
Currently the latest version.

**Comment by TWSSYesterday** [comment]
Any update on this @MattBDev ?

**Comment by MattBDev** [comment]
I haven't tested this yet. I'll do it right now

**Comment by MattBDev** [comment]
@TWSSYesterday I can't reproduce it in 0.17 so I am going to try going back to 0.16.3 and testing

**Comment by MattBDev** [comment]
@TWSSYesterday I was not able to reproduce this

**Comment by TWSSYesterday** [comment]
play.primemc.org Prison server, a player reported it.

**Comment by MattBDev** [comment]
Thanks for the IP. I'll take a look

**Comment by MattBDev** [comment]
I still can't reproduce it

**Comment by TWSSYesterday** [comment]
Ok, thanks :)
