### ISSUE TITLE
SQLPlotMe error "out of memory

### ISSUE THREAD

**Issue by LivingXx** [WorldCretornica/PlotMe-Core#179]
Hi,i am a moderator on a minecraft server we are having trouble with our PlotMe plugin right now and could use some help!
We have just updated from PlotMe 0.13 to PlotMe 0.16 and we want to keep our plot world but everytime we try its comes up with this error:
1.02 14:51:31 [Server] INFO [14:51:31 ERROR]: PlotMeSQL exception on initialize :
11.02 14:51:31 [Server] INFO [14:51:31 ERROR]:   out of memory

We cant seem to find out how to fix it and help would be much appriceated!
Thanks!

EDIT: Out host has helped us fix it thanks for the help MattBDev!

**Comment by MattBDev** [comment]
I am not sure what is causing the SQL to run out of memory. Are you using MySQL or no? Also, was there any other error message that you can provide. If you do have a an error message, please use markdown format to paste it here.
