### ISSUE TITLE
Small bug with easy fix (bucket empty event)

### ISSUE THREAD

**Issue by Autom3** [WorldCretornica/PlotMe-Core#181]
Hey, I've found a small bug in the code. [link to code](https://github.com/WorldCretornica/PlotMe-Core/blob/master/src/bukkit/java/com/worldcretornica/plotme_core/bukkit/listener/BukkitPlotListener.java#L135)

For the location you look at which block is being clicked, shouldn't this be where the liquid is being placed? Because now people can not click the border of their plot to place a liquid, but what's more important is that they **can** place liquids outside their plot when clicking a block that's on their plot...

If you replace the line with this:
```java
BukkitLocation location = new BukkitLocation(event.getBlockClicked().getLocation().add(event.getBlockFace().getModX(), event.getBlockFace().getModY(), event.getBlockFace().getModZ()));
```

I think it should work?

**Comment by MattBDev** [comment]
I wasn't able to reproduce this. Can you upload a photo or video explaining?

**Comment by Autom3** [comment]
Yea no problem, http://gyazo.com/078d875eaff690a5d1cc273de7141bf8 here's one.
Pretty much right clicking a block that's in your plot, but touches the border, will place a sourceblock (not clientside confirmed) and it won't flow everywhere. Plot owners aren't able to remove the water afterwards (i think).

**Comment by ItsHarry** [comment]
I guess he means that you can not place water if you are clicking the slabs

![2015-02-14_14 59 22](https://cloud.githubusercontent.com/assets/914835/6199802/2a810f78-b45a-11e4-852c-d006b598788b.png)
