### ISSUE TITLE
Can't build in own plot if standing outside perimeter

### ISSUE THREAD

**Issue by ItsHarry** [WorldCretornica/PlotMe-Core#182]
You can't place/build blocks in your own plot if you're standing outside of its perimeter.

Not really a bug, but I don't think it's intended as it makes it hard to place certain blocks such as pistons in the correct direction, although I don't see why anyone would ever want to place pistons facing outwards of the plot.

If this is too much work to fix, go ahead and close this because it's really not very significant.

![0iifva2](https://cloud.githubusercontent.com/assets/914835/6173807/ee91d8aa-b2ea-11e4-8261-25afbd919070.jpg)

**Comment by MattBDev** [comment]
I would consider this a big bug.

**Comment by ItsHarry** [comment]
Alright, thanks

**Comment by MattBDev** [comment]
I can't see why this is happening but I am going to add some loggers to check.

**Comment by ItsHarry** [comment]
I should probably add that I'm using 0.16.3, not sure if that makes a difference.

**Comment by MattBDev** [comment]
Not really. the bug is still present in the latest dev build so it is still an issue. The loggers will help me determine where the check fails to work properly.

**Comment by jomo** [comment]
Weird, I am quite sure I fixed this in #12.

**Comment by MattBDev** [comment]
This is caused by an event listener outside of block place . not sure which one of them

**Comment by jomo** [comment]
My guess is [this WorldEdit listener](https://github.com/WorldCretornica/PlotMe-Core/blob/f94ee381416f163cc5a44b7b5a76174c402eebc4/src/bukkit/java/com/worldcretornica/plotme_core/bukkit/listener/BukkitPlotWorldEditListener.java#L140)

**Comment by ItsHarry** [comment]
Probably this line then:
```java
PlotId id = manager.getPlotId(player);
```

I assume this fetches the ID using the player's location, and not the block location.

**Comment by MattBDev** [comment]
I'll test my local server without worldedit to check.

**Comment by MattBDev** [comment]
@jomo @ItsHarry you're both right.

**Comment by MattBDev** [comment]
Fixed

**Comment by ItsHarry** [comment]
Awesome, thanks

**Comment by jomo** [comment]
> Weird, I am quite sure I fixed this in #12.

I actually [did](https://github.com/WorldCretornica/PlotMe-Core/pull/12/files#diff-f2b8dcd49fb5c3cfa59ea39c8f85da4fL131) :D

**Comment by MattBDev** [comment]
@jomo I was trying to improve performance by creating less objects but while doing so, I reverted what you did. My bad.

**Comment by jomo** [comment]
:sunglasses:
