### ISSUE TITLE
Expiration not working

### ISSUE THREAD

**Issue by ichUndSo2014** [WorldCretornica/PlotMe-Core#183]
I tried the command /p expired and it said there were no expired plots. I know that is wrong because when I tried /p info the expiration date was February 10th or earlier. The reset expired command also doesn't work. I am using 0.16.3 PlotMe on a Spigot server.

**Comment by MattBDev** [comment]
Please check your spelling and grammar next time you post an issue.

**Comment by MattBDev** [comment]
Can anyone confirm that these are not working?

**Comment by ichUndSo2014** [comment]
sorry for bad language i tried my best and this is badly not so much cause i am not a native speaker

**Comment by ichUndSo2014** [comment]
https://www.youtube.com/watch?v=3qVVt-bNLJw&feature=youtu.be

**Comment by MattBDev** [comment]
the reset expired command is a console only command

**Comment by ichUndSo2014** [comment]
ok and what is wrong with the /p expired command?

**Comment by MattBDev** [comment]
Not sure. I have to check in the code

**Comment by ichUndSo2014** [comment]
The reset expired command also dont work in the console. Both the /p expired command (ingame) and the /p resetexpired command (on cosole) are currently broken i think.

**Comment by MattBDev** [comment]
I still need feedback if this is working or not

**Comment by ichUndSo2014** [comment]
Both comments dont exist in version 2.8.12. The plugin tell me there is no such sub comment.

**Comment by MattBDev** [comment]
ich, what are you talking about? PlotMe is only on 0.16.3
I need to know if "/plotme resetexpired <worldname>" works or not.

**Comment by MattBDev** [comment]
This seems to be working as expected and there has been no feedback as to whether it is actually broken or not. This issue will be closed. If you believe this is a mistake please reply.
