### ISSUE TITLE
What is it the meaning “AutoLinkPlots"

### ISSUE THREAD

**Issue by GreatGBL** [WorldCretornica/PlotMe-Core#186]
I can not find this variable of configuration in http://plotme.worldcretornica.com/core-config.html

**Comment by jomo** [comment]
From [the old plugin site](http://web.archive.org/web/20140911012253/http://dev.bukkit.org/bukkit-plugins/plotme/pages/configuration):
> When this is true, a players plots are linked together.

I found [this piece of code](https://github.com/WorldCretornica/PlotMe-Core/blob/5befedd6c6152aade1822204bfd428cdfd455c58/src/main/java/com/worldcretornica/plotme_core/PlotMeCoreManager.java#L344) which is commented out and no longer used, but it seems like it was used to fill the road between plots, "linking" them together

**Comment by jomo** [comment]
Just found this picture:

![screenshot](http://dev.bukkit.org/media/attachments/50/573/2014-06-28_13.32.41.png)

Note how the plot in the background spans over the size of the two plots in the foreground

**Comment by GreatGBL** [comment]
@jomo 

Aha, Thanks for your help. If I set it FALSE ,the road will be disappeared?

**Comment by MattBDev** [comment]
The config does nothing. I have left it there so when the feature is available, it can be used.

**Comment by BillyGalbreath** [comment]
Welp. This feature alone was the entire reason I installed this plugin. How disappointing :(
