### ISSUE TITLE
User Question: How do I create two plotworlds?

### ISSUE THREAD

**Issue by Hajikiller** [WorldCretornica/PlotMe-Core#187]
I am trying 2 have 2 plotme worlds. I tried to just put 2 of the same information into config and just change name but when I save it replaces old one with the new. The new plot world works just fine but my old plot world says that it is not a plot world. How do I fix this?

**Comment by MattBDev** [comment]
I am not sure why it would replace the old world information with the stuff from the new world. When you added the new world did you add it to both the generator and normal plotme config files?

**Comment by Hajikiller** [comment]
Yes

**Comment by MattBDev** [comment]
Yes is really not a helpful answer. I need more details such as your version of plotme, the config files, and the bukkit/spigot version.

**Comment by Hajikiller** [comment]
I am using Bukkit version 1.7.9-RO.2 plotme version v0.13f. I am also using
McProhosting and plotme config is

worlds:
  plotworld2:
    PlotAutoLimit: 1000
    PathWidth: 7
    PlotSize: 72
    BottomBlockId: '7'
    WallBlockId: '44'
    PlotFloorBlockId: '2'
    PlotFillingBlockId: '3'
    RoadMainBlockId: '24:'
    RoadStripeBlockId: '24:1'
    RoadHeight: 64
    DaysToExpiration: 7
    ProtectedBlocks:
    - 54
    - 61
    - 62
    - 120
    - 94
    - 93
    - 84
    - 25
    - 355
    - 118
    - 117
    - 138
    - 140
    - 145
    - 23
    - 158
    - 154
    PreventedItems:
    - '351:15'
    - '259'
    - '328'
    - '343'
    - '342'
    - '408'
    - '333'
    ProtectedWallBlockId: '44:4'
    ForSaleWallBlockId: '44:1'
    AuctionWallBlockId: '44:1'
    AutoLinkPlots: true
    DisableExplosion: true
    DisableIgnition: true
    economy:
      UseEconomy: false
      CanPutOnSale: false
      CanSellToBank: false
      RefundClaimPriceOnReset: false
      RefundClaimPriceOnSetOwner: false
      ClaimPrice: 0.0
      ClearPrice: 0.0
      AddPlayerPrice: 0.0
      DenyPlayerPrice: 0.0
      RemovePlayerPrice: 0.0
      UndenyPlayerPrice: 0.0
      PlotHomePrice: 0.0
      CanCustomizeSellPrice: false
      SellToPlayerPrice: 0.0
      SellToBankPrice: 0.0
      BuyFromBankPrice: 0.0
      AddCommentPrice: 0.0
      BiomeChangePrice: 0.0
      ProtectPrice: 0.0
      DisposePrice: 0.0
usemySQL: false
mySQLconn: jdbc:mysql://localhost:3306/minecraft
mySQLuname: root
mySQLpass: password
globalUseEconomy: false
AdvancedLogging: false
Language: english
allowWorldTeleport: true
defaultWEAnywhere: false
auto-update: false
allowToDeny: true

**Comment by MattBDev** [comment]
Your version is no logner supported so this ticket is closed. Please do not file a ticket unless you are using the most up to date version.
