### ISSUE TITLE
Config's: HOCON or YAML? 

### ISSUE THREAD

**Issue by MattBDev** [WorldCretornica/PlotMe-Core#188]
In order to be compatible with both Sponge and Bukkit/Spigot, a configuration type needs to be picked. Sponge will be using HOCON but Bukkit/Spigot is currently using YAML.
HOCON is a JSON subset that allows comments and it will be closely related to the configuration format Mojang will be using when the Minecraft API is available for use. Details about HOCON can be found at this link: https://github.com/typesafehub/config/blob/master/HOCON.md
YAML is the current format being used and I don't feel like I need to describe it much since most people are currently aware of it. HOCON will not be too confusing if we switch to it and there will be a guide to go along with it to show how to edit it. There will be comments provided with HOCON to describe each config option.

**I am looking for opinions of others to decide what to use**

**Comment by MarkusAV** [comment]
I don't see any problems switching :ok_hand:

**Comment by ItsHarry** [comment]
In my opinion, you should just keep YAML. If it ain't broke, don't fix it

**Comment by Burgerz42** [comment]
In my opinion, YAML is working fine for us, and I don't see many HCON files out there. I think it would be very confusing to have this.

**Comment by jomo** [comment]
I agree with @ItsHarry, YAML works great. In fact, you can even use JSON and it's still valid YAML.
YAML supports comments as well and it's even possible to set the type of the value in YAML.

----

When you compare YAML, JSON and HOCON I think YAML is the most user-friendly thing to use.
Does HOCON have any advantages over YAML?

**Comment by MattBDev** [comment]
The negatives about YAML is that a lot can go wrong and it isn't really "beginner friendly".
HOCON's advantages are:
* more languages support it, also web-browsers
* Beginner friendly
* human-readable
Downsides include more brackets and possibly less features. I think I will stick with YAML and use a library for import instead of depending on Bukkit's system so I can use Sponge.

**Comment by jomo** [comment]
> more languages support it, also web-browsers

I'm *very* sure YAML has more parsers than HOCON does. Which web browser can read HOCON files (and what would they do with them)?

> Beginner friendly

Hmm I think YAML would be more beginner friendly than HOCON.

**Comment by MattBDev** [comment]
I think we will be sticking with YAML due to overwhelming support for it.

**Comment by Burgerz42** [comment]
:D

**Comment by MarkusAV** [comment]
Closing this then :smile:
