### ISSUE TITLE
Spawning mobs/animals 

### ISSUE THREAD

**Issue by theshadyonehd** [WorldCretornica/PlotMe-Core#189]
can you add a setting to restrict players to only spawning mobs/animals on there on plots?

**Comment by MattBDev** [comment]
I will be adding this later today.

**Comment by theshadyonehd** [comment]
:) :+1:

**Comment by MattBDev** [comment]
@theshadyonehd When you submitted this, did you mean that players could spawn animals with spawn eggs?  I am working on that right now. The issue will be closed as soon as I submit the Commit for it but if it closes, please still reply.

**Comment by theshadyonehd** [comment]
Sorry for the late reply.

Yep, I meant spawning animals with spawn eggs. Another addition could be a limiter of animals per plot maybe?

**Comment by MattBDev** [comment]
@theshadyonehd I will revist limiting animals per plot after version 0.17 is ready
