### ISSUE TITLE
Biome Issue

### ISSUE THREAD

**Issue by Gikka218** [WorldCretornica/PlotMe-Core#194]
I'm pretty sure the default biome of the plotme world is supposed to be plains, like all other superflat worlds, but the biomes in my plotme world are the normal randomly generated ones. Is this intended? If not, is there a fix?

Also, my other multiverse superflat worlds have been doing the same thing. 

Any help would be appreciated. Thanks.

**Comment by MarkusAV** [comment]
You can select what type of biome you'd like to have using the /plot biome command

**Comment by Gikka218** [comment]
But isn't that command only for the plot(s) you own? I need the biome changed for the ENTIRE world.

**Comment by MarkusAV** [comment]
Yes, it's for the individual plot. It's not possible to have a biome for the entire world tho, but I can mark this issue as an improvement.

**Comment by EvilOlaf** [comment]
As you wrote your other - propably not PlotMe related - flat worlds have the same issue. So it seems that there is something with your server config at all ^^

Usually you can fix the biome issue of PlotMe by adding -t flat to your mv create command.

**Comment by Gikka218** [comment]
Thanks, I'll look around a bit in the config and see if I find anything related to biomes.

**Comment by MarkusAV** [comment]
Just tested what Olaf said, and it seems to work. Nice one :)
´´´/mvcreate plotworld -g PlotMe-Generator -t flat´´´ will fix it.. however, this is only if you have Multiverse tho.., I don't know if it's possible to do this without Multiverse?

**Comment by MattBDev** [comment]
This was a plotme issue in 0.13f but that version is not supported anymore and this is not the place to report bugs for that version

**Comment by EvilOlaf** [comment]
Good question, never created a world without world management plugin =)

**Comment by Gikka218** [comment]
Sorry about that, I didn't realize my version was outdated. I updated the plugin and now it's fixed. Thanks for the help!
