### ISSUE TITLE
Plotme couldn't protect the armor_stand

### ISSUE THREAD

**Issue by GreatGBL** [WorldCretornica/PlotMe-Core#196]
Hello , my server is 1.8 online server , I find the plotme plugins could not protect the arrmor_stand ,it means someone can steal the armor

**Comment by GreatGBL** [comment]
The biggest issues is the arrmor_stand is the entity not the block , so I can not edit the config to protect this

**Comment by MattBDev** [comment]
If I was to protect this, I would have to sacrifice 1.7 support. More than half of plotme users are using 1.7

**Comment by GreatGBL** [comment]
Enn.. So I just temporary ban use arrmor_stand in plotworld .Thx for your help

**Comment by MattBDev** [comment]
I will leave the issue open because it is a bug.

**Comment by GreatGBL** [comment]
in 5bbd3c7  ?  means it was update ?
