### ISSUE TITLE
BottomBlockId 

### ISSUE THREAD

**Issue by PrisonHeist** [WorldCretornica/PlotMe-Core#197]
I'm having problem with setting the BottomBlockId, when I edit my config.yml and put BottomBlockId: '7' then do /plotme reload this line gets automatically removed from the configuration. Have also tried shutting down server changing config then starting back up, still removes it.

I am using dev build 71 from 09-Feb-2015 14:11:45. I cannot use any builds newer than this as I get an error when doing /p h (See issue #175)

**Comment by MattBDev** [comment]
That config was removed. If it is not listed on the website then it doesn't exist
