### ISSUE TITLE
Offline Support

### ISSUE THREAD

**Issue by MattBDev** [WorldCretornica/PlotMe-Core#199]
After talking to BukkitDev mods, I have found that the rules were not particularly clear. We are allowed to offer offline support as long as we are not supporting ONLY offline servers. This topic is still tricky because unless a server has a plugin that can manipulate and control an Offline UUID the UUID of the player will change because their name changed. This change will be in versions after 0.17 but not in 0.17 (if it is a feasible option)

**Comment by EvilOlaf** [comment]
Sounds good.
Anyway I would prefer not to support offline servers because the most common reason to have a server in offline mode is still piracy I think.

**Comment by MattBDev** [comment]
It may not happen but I am not going to be worrying about this until after 0.17 due to the massive SQL Rewrite.

**Comment by orkun1675** [comment]
Offline mode does not mean piracy.
Why? Well not all people can pay 20 euros for a game, and mojang doesn't force you to. And these people deserve the right to play together with their friends, just like rich people do. Offline servers are thus necessary to have fun for all, as long as they don't violate the EULA in any case.

@MattBDev first of all thank you for looking into this. After running some tests on an offline mode server I can say that the only issue is PlotMe purging data of plots who don't have a Mojang validated UUID from the MySQL database. Offline mode servers do not allow name change. All players are authenticated by their username just as in MC 1.7. So if PlotMe does not force Mojang validation, all would be fine.

**Comment by MattBDev** [comment]
@orkun1675 I need to make a valid check to give these players a UUID and that they will not be removed with the Mojang Validation. This will be fixed in 0.18

**Comment by orkun1675** [comment]
@MattBDev is this coming soon with 0.17 ?

**Comment by MattBDev** [comment]
@orkun1675 Offline Support may come early due to changes I had to make internally but I am not sure how I would retrieve names based on offline UUID's

**Comment by MattBDev** [comment]
While redesigning the way plotme handles names and UUID's I am making sure offline support will be included.

**Comment by orkun1675** [comment]
Okay that's great!

**Comment by MattBDev** [comment]
Will be fixed sooner than expected.

**Comment by MattBDev** [comment]
A fix is coming in the form of a dev release later today :smile:

**Comment by MattBDev** [comment]
Offline support is now added!
