### ISSUE TITLE
Players Cannot Destroy Blocks

### ISSUE THREAD

**Issue by poopnozle** [WorldCretornica/PlotMe-Core#200]
After a player claims their plot they can place blocks but not break them afterwards. My spawn protect is set to 0 and I'm sure of it. Is it a plugin interfering? Is there a list of plugins that may cause this issue anywhere?

**Comment by MattBDev** [comment]
What plugins are you using? It is easier to list only the ones you use rather than me list plugins that can cause issues

**Comment by poopnozle** [comment]
ActionAnnouncer, BetterBroadcasts, CommandSigns, CS-CoreLib, EmeraldEnchants, Essentials (All of them + groupmanager), EZPrestige, EZRanks, ItemRenamer, Multiverse-Core, NoPL, PlotMe, PrisonGems, PrisonMine, PrisonSuite, PrisonUTILs, QuickSell, StarterKit, TimTheEnchanter, Vault, WGCustomFlags, WorldEdit, WorldGuard, WorldGuard_FlyStop

**Comment by MattBDev** [comment]
Disable WorldGuard for plotworld.

**Comment by poopnozle** [comment]
How would I do that? I don't see an option for that anywhere.

**Comment by poopnozle** [comment]
Also, block breaking only works while in creative mode. Even for OP's.

**Comment by MattBDev** [comment]
@poopnozle I am going to request that you ask for help on the forums as this is area is for valid bugs in the plugin itself. What you are looking for is setting up the plugin on the server which is not what this section is for. Link to the forums: http://www.spigotmc.org/threads/plotme-official.37327/page-55
