### ISSUE TITLE
/p reset should reset biome

### ISSUE THREAD

**Issue by Bobcat00** [WorldCretornica/PlotMe-Core#202]
The /p reset command should also reset the plot's biome back to default.

**Comment by MattBDev** [comment]
It doesn't do that already? looks like a bug.

**Comment by Bobcat00** [comment]
Did some more testing.  /p reset does reset the biome, but the client shows the old biome (even in the F# info) until the player relogs.  So I don't know if PlotMe could force an update to the client or not.  If not, I guess you could close this.

**Comment by EvilOlaf** [comment]
This can not be fixed by PlotMe.

https://github.com/WorldCretornica/PlotMe-Core/issues/41

**Comment by MarkusAV** [comment]
@EvilOlaf :+1:
