### ISSUE TITLE
Invaild Generator! "PlotMe-DefaultGenerator". Aborting World Creation

### ISSUE THREAD

**Issue by lucasdow1** [WorldCretornica/PlotMe-Core#203]
Hello,

When i do /mv create plotworld normal -g PlotMe-DefaultGenerator i get this comment "Invaild Generator! "PlotMe-DefaultGenerator". Aborting World Creation" I have checked the config and everything and everything is right. Can you please help me?

Thanks
Lucas Dow

**Comment by EvilOlaf** [comment]
Make sure that PlotMe-DefaultGenerator has been load properly on server startup.

**Comment by lucasdow1** [comment]
Yes it has been.

**Comment by lucasdow1** [comment]
Everything works. Just cant make the world.
