### ISSUE TITLE
Plotme config.yml, PREVENT items don't work

### ISSUE THREAD

**Issue by NickFirenzo** [WorldCretornica/PlotMe-Core#205]
I have a problem.. If i type any items for block on plotworld they don't work
Example:
I type at PreventedItems:
- '331' 
Number of item is 331 an type /plotme reload, but don't world look on picture..
PIC1: http://prntscr.com/67zqqi
PIC2: http://prntscr.com/67zr0q - I can use redstone, but in config.yml at plotme is prevent and doesen't work.. And others all items don't work for PREVENT!
Please help me what should i do, thanks..

**Comment by MarkusAV** [comment]
Where you OP/got all plotme permissions when you did this? Players who have all plotme permissions(or just plotme.unblock.#) and/or OP will bypass the prevented items listing.

**Comment by NickFirenzo** [comment]
No i'm not op, default member can place redstone, plotme config.yml don't work for prevent items..

**Comment by MarkusAV** [comment]
Did you try put the redstone in preventedBlocks?

**Comment by NickFirenzo** [comment]
redstone with latters or with number of item(ID)?

**Comment by MattBDev** [comment]
Are you trying to prevent some members from using Redstone but allowing others? If so, that is a violation of the Minecraft eula

**Comment by EvilOlaf** [comment]
Yes, if these members being charged for real cash. Otherwise it's ok.

**Comment by MattBDev** [comment]
I went back into the changelogs and found the original description on how Prevented Items was meant to work and be used:
 > This is the list of items which users cannot use on other players plots. If a player owns the plot, he can still use these items. Use a plugin like WorldGuard to block them for everyone.
Your use does not meet this description and the issue will be closed.
