### ISSUE TITLE
TnT Within Plots

### ISSUE THREAD

**Issue by Schneiderism** [WorldCretornica/PlotMe-Core#206]
I mainly just have a question regarding TnT and protection. Is there a way to make it so TnT can only destroy blocks that are in a users plot? I want it enabled, but don't want in wrecking the pathways. If it helps, I do use WorldGuard, so I was wondering if that would help?

Thanks for the help,

~Doobs

**Comment by MattBDev** [comment]
Please ask the community this question instead of filing this in the bug reports.
Link to the plotme forums: http://www.spigotmc.org/threads/plotme-official.37327/
I would answer this here but I don't remember the answer.

**Comment by jomo** [comment]
Shouldn't be too hard to implement though. You can just copy most of the code from the [StructureGrowEvent](https://github.com/WorldCretornica/PlotMe-Core/blob/95b8057b165b7d9284b7fa53b2643f0dc05b6c97/src/bukkit/java/com/worldcretornica/plotme_core/bukkit/listener/BukkitPlotListener.java#L445).

**Comment by MattBDev** [comment]
@jomo so is this not already in plotme?

**Comment by jomo** [comment]
Had a quick look and it seems like it's either disabled completely or it's disabled on roads. But that's only the explosion origin, not blocks affected by the explosion IIRC
