### ISSUE TITLE
PlotMe : Worldedit bug.

### ISSUE THREAD

**Issue by phantomrider34** [WorldCretornica/PlotMe-Core#211]
You can use WorldEdit to destroy plots on PlotMe servers.
This can be done by the /repl command, but I go into more detail in my WorldEdit report.
(http://youtrack.sk89q.com/issue/WORLDEDIT-3270)
Plots can be griefed due to blocks on the plot being replaced by your chosen block in the /repl 
command. (This should be blocked inside and outside of plots that you do not own)
The server I play on uses the latest version of both plugins.

**Comment by jomo** [comment]
Any command that isn't limited by the gmask is able to modify blocks.

**Comment by MattBDev** [comment]
Fixed for 0.17
Some of the fixes are included in c1c2c1e271cc03ab6a91697094a4e611490536b9
