### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [WorldCretornica/PlotMe-Core#212]
http://pastebin.com/9di2N5s9

**Comment by EvilOlaf** [comment]
Please use either markdown (https://guides.github.com/features/mastering-markdown/) or pastebin to send logs. No one wants to read this unformatted waste.

**Comment by TheOnlyRealTGS** [comment]
It was short, that's why I didn't bother.

**Comment by EvilOlaf** [comment]
Even though everyone would appreciate if it is formatted in some way ;)

**Comment by MattBDev** [comment]
I have a fix in the next dev release that builds. The dev releases are extremely unstable and should not  be used. (All except for the one recommended on the resource page)

**Comment by TheOnlyRealTGS** [comment]
Oh, okay.
