### ISSUE TITLE
Updating old server- org.apache.commons.lang.UnhandledException: Plugin PlotMe v0.17-

### ISSUE THREAD

**Issue by ProsperCraft** [WorldCretornica/PlotMe-Core#214]
I am updating a really old server, I just loaded in and have not been into the plotworld yet.

I get this when loading in the first time during startup with the latest snapshot- build 103

[06:58:35 WARN]: Exception in thread "Craft Scheduler Thread - 10"
[06:58:35 WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotMe v0.17-SNAPSHOT generated an exception while executing task 6
>       at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
>       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>       at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
>       at com.worldcretornica.plotme_core.storage.Database$2.run(Database.java:332)
>       at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
>       at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
>       ... 3 more
>

Then when doing /plotme auto plotworld I get the message below.

[07:00:43 INFO]: Mobeous issued server command: /plotme auto plotworld
[07:00:43 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'plotme' in plugin PlotMe v0.17-SNAPSHOT
>       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot_server.jar:git-Spigot-35348a5-ee6d0fa]
>       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot_server.jar:git-Spigot-35348a5-ee6d0fa]
>       at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot_server.jar:git-Spigot-35348a5-ee6d0fa]
>       at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot_server.jar:git-Spigot-35348a5-ee6d0fa]
>       at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot_server.jar:git-Spigot-35348a5-ee6d0fa]
>       at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot_server.jar:git-Spigot-35348a5-ee6d0fa]
>       at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot_server.jar:git-Spigot-35348a5-ee6d0fa]
>       at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot_server.jar:git-Spigot-35348a5-ee6d0fa]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_75]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]
>       at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot_server.jar:git-Spigot-35348a5-ee6d0fa]
>       at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot_server.jar:git-Spigot-35348a5-ee6d0fa]
>       at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot_server.jar:git-Spigot-35348a5-ee6d0fa]
>       at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot_server.jar:git-Spigot-35348a5-ee6d0fa]
>       at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.NullPointerException
>       at com.worldcretornica.plotme_core.PlotMeCoreManager.isPlotWorld(PlotMeCoreManager.java:522) ~[?:?]
>       at com.worldcretornica.plotme_core.commands.CmdAuto.exec(CmdAuto.java:29) ~[?:?]
>       at com.worldcretornica.plotme_core.bukkit.BukkitCommand.onCommand(BukkitCommand.java:153) ~[?:?]
>       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot_server.jar:git-Spigot-35348a5-ee6d0fa]
>       ... 14 more

**Comment by MattBDev** [comment]
If you are not running the development build as listed on the website, I cannot help you. Development builds are not recommended unless needed.
