### ISSUE TITLE
[Bug] Plot world generation broken

### ISSUE THREAD

**Issue by godleydemon** [WorldCretornica/PlotMe-Core#218]
Seems I'm getting a server crash on attempting to generate a plot world on first server run without trying to generate any other worlds. 

Latest.log: http://pastebin.com/G6aMXKut
Crash report: http://pastebin.com/jBxF001r

I'm using
Plotme: Build #110
Plotme Generator: Build #41

spigot.yml: http://pastebin.com/M2KZnD2n
bukkit.yml: http://pastebin.com/pG25ndVw
server.properties: http://pastebin.com/jL1AR09D

All other settings in plotme have been left at there default settings and haven't been touched. Would appreciate some help on this :)

**Comment by MarkusAV** [comment]
If you left the files of PlotMe untouched, then you didn't change the worldname? The default world of PlotMe is "plotworld". In your Bukkit.yml, rename "world" to "plotworld" and I'm pretty sure you'll be all set!
For further instructions, visit http://plotme.worldcretornica.com
