### ISSUE TITLE
Unable to create new plotworld in 1.8

### ISSUE THREAD

**Issue by flatbmx** [WorldCretornica/PlotMe-Core#222]
When creating a new world using either latest builds from spigot or dev builds exception is thrown while generating chunk then world is bugged in mv.

http://pastebin.com/ym7YxauW

**Comment by EvilOlaf** [comment]
Did you setup a world called `test` in your PlotMe config and PlotMe-DefaultGenerator config properly?

**Comment by flatbmx** [comment]
Yes, I have the corrent setup for the world in mv/plotme/plotme-defaultgenerator and it still fails.

**Comment by MattBDev** [comment]
This issue was not reported in the right section but it is being worked on because someone did submit a ticket before you in the right place. I will be closing this ticket and will give you the link to the other ticket as soon as I can

**Comment by MattBDev** [comment]
@flatbmx @EvilOlaf the issue can be tracked here: https://github.com/WorldCretornica/PlotMe-DefaultGenerator/issues/10
