### ISSUE TITLE
How can I disable dispensors

### ISSUE THREAD

**Issue by YepImRobbie** [WorldCretornica/PlotMe-Core#223]
Dispensers are a really big problem since people are making sand fall into the cobweb then getting tnt to make it blow out onto the roads and plots.

**Comment by MattBDev** [comment]
This is not a bug nor a suggestion so your post should have not been made here. Next time, please use the spigot forums to ask a question like this.
PlotMe does not offer any way to disable a block in a world. Plugins like WorldGuard are what you are looking for. I hope this helps you.
