### ISSUE TITLE
no flat

### ISSUE THREAD

**Issue by Gerbia** [WorldCretornica/PlotMe-Core#224]
hello think a world of plots like the tutorial says

/ mv create {NAME} Normal -g PlotMe-DefaultGenerator

changing the {NAME} per plot

but I believe a normal world, not a plane or flat.

help

**Comment by EvilOlaf** [comment]
To cut a long story down: What?

**Comment by Gerbia** [comment]
create a world with comendo .. but instead of a flat world divided into plots created a normal world is created

**Comment by EvilOlaf** [comment]
Then you did not setup PlotMe properly.
Read the installation instructions carefully: http://worldcretornica.github.io/PlotMe-Core/setup.html

**Comment by Gerbia** [comment]
if so did

put this / mv create parcela1 regular -g PlotMe-DefaultGenerator

I get faild

if I put this / mv create parcela2 regular -g PlotMe

the world is created but no plot and no plane
