### ISSUE TITLE
PlotMe wont load correctly

### ISSUE THREAD

**Issue by FiveStarHD** [WorldCretornica/PlotMe-Core#225]
when i put in /mv create plotworld normal -g PlotMe-DefaultGenerator it loads but when i tp to the world using /mv tp plotworld then it just takes me to a usual survival world i dont know what to do anymore im running 1.8 spigot and multiverse

**Comment by MattBDev** [comment]
In the future, something like this is better suited for the forums as it is not a bug.
If you are not getting console errors then I can't explain the behavior. I recommend following the steps on the website on adding the world to the bukkit.yml
