### ISSUE TITLE
Players can steal items from item frames

### ISSUE THREAD

**Issue by areqpl** [WorldCretornica/PlotMe-Core#228]
Hello, right now anyone can just take out any item from any item frame on any plot. It makes item frames pretty useless. Please fix the issue.

**Comment by MattBDev** [comment]
I cannot reproduce this issue. This has been fixed MULTIPLE times.
Please provide the following information: Bukkit/Spigot Version, Minecraft Version, and how to reproduce.

**Comment by MattBDev** [comment]
I would also like to note that if you do not follow up in the next 24 hours, this issue will be closed. I am running on a tight timeline atm.

**Comment by jomo** [comment]
@MattBDev you can create a `CONTRIBUTING.md` file where you ask for the details you always need plus some general guidelines. GitHub will show everyone this notice when they open an issue or PR:
![contributing screenshot](https://i.imgur.com/FfaoJK5.png)

**Comment by areqpl** [comment]
Spigot version: 1646, MC 1.7.10
PlotMe version: 0.16.3, but I also tested on the newest development build
To reproduce, you hit item frame with your hand, then the item inside of frame drops out.

**Comment by MattBDev** [comment]
I am still not able to reproduce and the next version of PlotMe will only support MC 1.8/1.8.3
