### ISSUE TITLE
Pulling blocks with Sticky pistons

### ISSUE THREAD

**Issue by WillyBee55** [WorldCretornica/PlotMe-Core#232]
A user can pull the border of their plot inwards by using a sticky piston. They can not push the slab back into it's spot however, making extra work for myself. If that could fixed, that would be wonderful.

This is the piston before
http://i.imgur.com/Eozbwqk.png

After being activated, it pulled the slab
http://i.imgur.com/yc3wTJ7.png

Piston is activated, but not able to push slab back onto the border.
http://i.imgur.com/iWMw3dC.png

**Comment by jomo** [comment]
Weird, I fixed that in #23. Which version are you using?

**Comment by MattBDev** [comment]
Fixed in a recent commit. It is already fixed for 0.17

**Comment by MattBDev** [comment]
@WillyBee55 thank you for the report and the detail you put into it. I appreciate it. If you find more bugs, let me know :smile:
