### ISSUE TITLE
Plot Remove All

### ISSUE THREAD

**Issue by SecretlyJealous** [WorldCretornica/PlotMe-Core#233]
/plot remove all - This would essentially remove all added players to the plot. Players mainly roleplay on my server and sometimes have over 25 users added to the plot, it can be a hassle removing every single player you've added to your plot.

**Comment by MattBDev** [comment]
I'm suprised this wasn't around in the first place since the code already exists. I will add it but the permissions will be the same as plot add and plot remove

**Comment by jomo** [comment]
Please implement this using `/plotme remove *`. There is a user named [all](https://api.mojang.com/users/profiles/minecraft/all).

**Comment by EvilOlaf** [comment]
Facepalm

**Comment by jomo** [comment]
*(it would also be consistent with [`/p deny *`](https://github.com/WorldCretornica/PlotMe-Core/blob/3c7230ec0988fbe35a670c0bc9e8180e44a62e38/src/main/java/com/worldcretornica/plotme_core/commands/CmdDeny.java#L81))*

**Comment by MattBDev** [comment]
Why did mojang allow players with 3 character usernames.....

**Comment by jomo** [comment]
They had that since forever, see [ez](https://api.mojang.com/users/profiles/minecraft/ez) (Notch's ex-wife)

**Comment by MattBDev** [comment]
This should be partially implemented in the current code. It will be finished as soon as I review the code before release. I will mark this as complete since it technically is.
