### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by ThisTNTSquid** [WorldCretornica/PlotMe-Core#234]
when using /plotme , it said "An internal error occurred while attempting to perform this command"
and the server log is here http://pastebin.com/n4thGCdk 

Plugin installed:
- world Edit
- Essentials
  - Core
  - Chat
  - Protection
- multiverse
  - core
  - inventory
  -portal
- lockette

**Comment by EvilOlaf** [comment]
You are using an outdated version of PlotMe. Update to the latest available version and see if this issue has been resolved.
