### ISSUE TITLE
Connecting plots!

### ISSUE THREAD

**Issue by Grummpy14** [WorldCretornica/PlotMe-Core#236]
Hey There! I have a question about how to use your plugin. I am currently on a server called aviatorcraft and they use you plugin. They have 50x50 block plots and i have a 3x3 ploted area that i have. Which is 9 plots in a square and they have 5 wide path ways around the plots now what I've tried figuring out how to connect the plots over the path ways. i have talked to the owners and they say they have tried it before. If You could get back to me asap with some sort of answer to my problem that would be wonderful. I have bin told by the staff of the server that if there is a way they will do it. they just don't know so i am here tiring to figure it out for sure.

**Comment by MarkusAV** [comment]
#221
