### ISSUE TITLE
API feedback

### ISSUE THREAD

**Issue by gdude2002** [WorldCretornica/PlotMe-Core#237]
Noticed that your [spigot release](http://www.spigotmc.org/resources/plotme-official.2131/) asks for API feedback, and I [just added PlotMe support](https://github.com/TheArchives/Painter/blob/master/src/main/java/com/archivesmc/painter/integrations/PlotMeIntegration.java) to one of my plugins, [Painter](http://dev.bukkit.org/bukkit-plugins/painter/). I've yet to test it, though, since I don't personally use PlotMe.

Anyway, what's up with the whole `Plot` vs `PlotId` business? This is the process I followed, feel free to correct me if I'm doing this wrong.

* Grab a `PlotId` from an `ILocation`, which is aware of what world it points to
* Grab the actual `Plot` using the `PlotID` (Constructed from a location that is aware of its world), and an `IWorld`
* Check `plot.isAllowed(UUID)` to see if they can build

This seems a little weird to me - Why are there distinct `PlotId`s? If we must have them, why are they not aware of their world? Or, perhaps, why are there no convenience functions to get a `Plot` without having to worry about `PlotIds`?

I'm aware that these are pretty minor complaints, and you guys make a great plugin, but I thought I'd provide some small feedback. Keep up the good work o/

**Comment by MattBDev** [comment]
Thank you so much for this feedback! I have been desperately trying to recieve feedback for weeks now.
A `PlotId` is the coordinates of the plot and I have been debating on whether I should have included the world with it to make it simpler for the code. `PlotId` is a new class in 0.17 and I am happy I haven't released that version yet because adding the world (as a `String` or `IWorld` due to Sponge compatibility) would certainly be a big improvement and make the code easier to use.
A convenience function is something I would need to look into because there may be some problems such as the plot returning null or the id returning null. I certainly think it should be easier to retrieve the Plot though and luckily, compared to 0.16 it is. 
I will leave this Issue open for active discussion.

**Comment by MattBDev** [comment]
Actually, it may not be possible to add the world to `PlotId`. I need to inquire to the sponge team about this.

**Comment by gdude2002** [comment]
Yeah, I can understand abstractions for various server types (How is the sponge API going, by the way? Are you using Yaml for your configs instead of that odd HOCON stuff?).. Personally, I see nothing wrong with returning null if something further down the stack also returns null, and would be happy to check that - It occurred to me that I'm actually not checking that right now and probably should be, lol, so I should go fix that.

Yeah, it felt kind of odd to be specifying the world along with something that was constructed with something else that was aware of the world, but at the same time, it's quite usable. Just a little silly, in my opinion.

Are you having that much trouble getting feedback? That strikes me as weird, given how insanely popular PlotMe actually is.

---

> Actually, it may not be possible to add the world to PlotId. I need to inquire to the sponge team about this.

Well, Sponge is based on Forge anyway, and Forge definitely has worlds.

**Comment by MattBDev** [comment]
Yeah. No one wants to give feedback to me although I keep begging for it. At the moment it looks like SnakeYAML is going to be packaged with PlotMe but I am looking into seeing if I can abstract the config stuff to work with Sponge's HOCON config.

**Comment by gdude2002** [comment]
I've been planning on using SnakeYAML as well, although I've been wary of doing so because one of the devs stated that he hates YAML and may make the server crash if a plugin uses it - although I'm not entirely convinced that'll happen.

**Comment by DefinitlyEvil** [comment]
@MattBDev Well I think you might wanna look a Bukkit API source code, it has a already-well-made configuration load/save system. :) And SnakeYAML is a good choice I think.

**Comment by DefinitlyEvil** [comment]
I just randomly looked at the PlotMe API feedback page and I found you. xD @gdude2002

**Comment by gdude2002** [comment]
Goddamnit @DefinitlyEvil, we're both everywhere :P

**Comment by MattBDev** [comment]
@DefinitlyEvil I already have a modified version of their library implemented in the next version but their library is built on SnakeYAML

**Comment by DefinitlyEvil** [comment]
@gdude2002 XD 

@MattBDev I know, you can just include SnakeYAML into your plugin. ;)

**Comment by MattBDev** [comment]
@DefinitlyEvil SnakeYAML is very big....I am hoping I can find a solution where I won't have to include it.

**Comment by gdude2002** [comment]
SnakeYAML is basically all there is that's well-maintained and reliable as far as I can see.

You may not have to include all of it though - Why not experiment with JarJar?

**Comment by DefinitlyEvil** [comment]
@MattBDev Well you may develop your own YAML parser if you want. xD It's possible but takes time though. :O

**Comment by jomo** [comment]
there is https://github.com/EsotericSoftware/yamlbeans too. Writing your own YAML parser is going to end up in a bigger project than PlotMe itself.

**Comment by DefinitlyEvil** [comment]
@jomo True.

**Comment by gdude2002** [comment]
Yeah, there's no need or use in going down the "Not Invented Here" path. There is YamlBeans, yeah, but I can't say I've heard much about it. Do you use it, @jomo?

**Comment by jomo** [comment]
Nope, found it on the YAML website

**Comment by MattBDev** [comment]
I am now minimizing the jar while shading in maven. It shrinks it a tiny bit but it looks like all a majority of the classes in SnakeYAML are needed. I am going to continue using it for the time being.

**Comment by DefinitlyEvil** [comment]
Your plugin is awesome, people won't mind the size of it is big. ;)

**Comment by MattBDev** [comment]
The size should be significantly decreased soon. I deleted more than 2,000 lines of code. Unless there is a lot of unoptimized stuff left, it should be smaller.

**Comment by DefinitlyEvil** [comment]
Okay. xD

**Comment by MattBDev** [comment]
People do care about the size of the plugin unfortunately.

**Comment by DefinitlyEvil** [comment]
Well, Windows is huge and Linux is tiny but people still use Windows. :) You should just concentrate on your project.

**Comment by gdude2002** [comment]
As a server admin with constrained space, I usually won't care too much if a plugin is a few MBs extra. However, a bunch of plugins like this quickly add up.

Also, you have the interests of the major server hosters to think about, and they'll be trying to put as many servers on one machine as they possibly can (which is unfortunate, but that's how it goes)

**Comment by DefinitlyEvil** [comment]
Oh god, that's true. :(

**Comment by MattBDev** [comment]
@gdude2002 in the latest few commits, although I broke the configs, I have made steps towards adding worlds to `PlotId`

**Comment by gdude2002** [comment]
\o/

**Comment by gdude2002** [comment]
@MattBDev What does it mean if a PlotId is null? And likewise, if a Plot is null?

I guess what I'm asking is whether I should allow or deny the edit, or if there's some config value I need to look up.

**Comment by MattBDev** [comment]
If a PlotID is null it will most likely mean that you are on the road. If a Plot is null, it means that the plot is not claimed, you are on the road, or something else went wrong.

**Comment by gdude2002** [comment]
@MattBDev Alright, but what should I be doing? And if this is on a world not managed by PlotMe, how do I find that out?

**Comment by MattBDev** [comment]
you can check if the world is a plotme world at the start of the event using isPlotWorld() which has many parameters. from there you can get the id and do a null check. If it is not null then you get the plot and do a null check on that. When doing these checks you should check the location of the block being modified (except for the world check).

**Comment by gdude2002** [comment]
I'm getting the Block anyway, the plugin is basically a simple way to replace blocks instead of just breaking and replacing them.

Part of my question is that I need to know what behavior is expected from such a plugin in each case. The PlotMe integration that I use is there so that one can't paint in someone else's plot, or other places they should be able to paint.

**Comment by MattBDev** [comment]
@gdude2002 a simple check to make sure if you are not in a plotworld:
https://gist.github.com/MattBDev/bcd98e47f35020bec277
This help?

**Comment by gdude2002** [comment]
@MattBDev I mean, what should be expected to happen as a result, eg can people paint on roads, etc

**Comment by MattBDev** [comment]
People won't be able to paint on roads if the id is null or the plot is null.

**Comment by gdude2002** [comment]
If the ID is null, or the plot is null, and the world is a plot world, I should deny the edit. Okay, that's what I needed, thanks. Is there an override that allows people to edit roads?

**Comment by MattBDev** [comment]
if they have the permission "plotme.admin.buildanywhere" they can edit roads.

**Comment by gdude2002** [comment]
Excellent, that's exactly what I needed. Thanks.

**Comment by DefinitlyEvil** [comment]
@gdude2002 But you should know that if player has that permission, they will be able to build on other player's plots so you may wanna add hooks or something to protect the plots by your own. :)

**Comment by gdude2002** [comment]
@DefinitlyEvil That is out of scope of my plugin

**Comment by DefinitlyEvil** [comment]
@gdude2002 Okay. xD

**Comment by MattBDev** [comment]
In my next commit on the refactor-0.17 branch, I will be changing the way people should be retrieving plots. It is much simpler than it used to be and there should be very little need to use the PlotId class. The method getPlot() will have multiple parameter options and return null if there is no plot (either the plot is not claimed or you are on a road).

**Comment by MattBDev** [comment]
I have also removed world/location from the PlotId class due to errors if trying to use plotme source when you aren't even using a server (see LegacyConverter)

**Comment by MattBDev** [comment]
I have added this feature for the next version of the API. I plan on adding more after 0.17 too.
