### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ITzOwen** [WorldCretornica/PlotMe-Core#238]
I have had PlotMe for my prison server, but for some reason for some people it keeps on saying, "Internal Server Error." It happened to me once when I was just flying around in my plot.

When I look in the Console, the log says something about a Chuck Loading Error

Image: http://imgur.com/1tA5pYm

PLEASE HELP!

**Comment by MattBDev** [comment]
Your config is setup incorrectly, you are also using an old version of CraftBukkit that will soon no longer be supported.
