### ISSUE TITLE
Allowing players (or one specific player) to build on the streets? and setting street biome..?

### ISSUE THREAD

**Issue by FallenAngel114** [WorldCretornica/PlotMe-Core#239]
Hi! I don't know if this is possible at all, I've tried looking but I couldn't find anything. I want to know if there's away to allow players (or a specific player) to build on the plotme streets. "why would I want anyone to be allowed to build on the streets?" Because I gave 4 plots next to each other to a player who wants to be able to build on the streets as well. I would like to help do it myself but I have no idea what he wants to do.

Another question, is it possible to change the biome of the streets? They're automatically plains. The plots that this player has is Taiga with random plains stripes through the middle. I was wondering if there is a way to fix this?

Thanks!

**Comment by jomo** [comment]
#186

**Comment by FallenAngel114** [comment]
i dont understand...

**Comment by MattBDev** [comment]
@FallenAngel114 He meant to refer you to another issue but the issue he referred you to was a closed issue. This is a request that is very frequently asked for and can be found at #221. This issue will now be closed
