### ISSUE TITLE
Internal Server Error [More help please this time]

### ISSUE THREAD

**Issue by ITzOwen** [WorldCretornica/PlotMe-Core#240]
I still have the internal server error :(

PlotMe was ok for a day, and then it happened.

Tell me what I need to do in the config, [last time you said I did it wrong]

And tell me what version of CraftBukkit I need to have! Maybe I might have to switch to spigot! Help me a lot please! <3

Error: http://imgur.com/pei21Xy

PLEASE HELP

**Comment by MattBDev** [comment]
Your Plotme Config and Generator Config are setup improperly. Saying "PLEASE HELP" doesn't do anything. Opening another issue for something you already reported and many others have reported is not helpful either. Please use the spigot forums if you are still getting this error.

**Comment by MattBDev** [comment]
You also really should be using CraftBukkit 1.8.3

**Comment by ITzOwen** [comment]
not that helpful, WHAT did I do wrong in my config? What shall I edit?

**Comment by EvilOlaf** [comment]
No one has a second sight, so post your config.
