### ISSUE TITLE
Per World Commands Issue 

### ISSUE THREAD

**Issue by xAcrosonicx** [WorldCretornica/PlotMe-Core#241]
Hello, I was wondering how I can make it so when players are in my Prison World, they can do /plot h and get to the First Plots (PlotWorld) and not the Second plots (Creative). Right now when they are in Prison and do /plot h they go to Creative, but I want them to go to Plotworld, and I use PEX. Need help ASAP, thanks :)

**Comment by MattBDev** [comment]
This really isn't an *"issue"* more of a general question on how to do something.
Sadly, this is not yet possible. At the moment when you try doing */plot h*, it will teleport you to the oldest plot you own (If I recall correctly). I do have plans on modifying how plot home works. Although it is not exactly what you are looking for, I hope it helps you at least a little bit. I will be closing this issue but if you have feedback on my changes to the home command for 0.17 or any questions about it, check out issue #230.

**Comment by xAcrosonicx** [comment]
Thank you for the speedy reply! Plot home does not bring me to my oldest plot, it only brings me to the creative world plots. So, I have multiple plots in "plotworld" and zero in "creative" when I do /plot h it says "no plot home" (or something along those lines) because I haven't claimed any in the creative world. It seems to be only recognizing the creative world for any plot commands, unless I am in "PlotWorld", then they all work. If this doesn't make sense, feel free to let me know and we could hop on my server and I can show you.

**Comment by MattBDev** [comment]
Try modifying allowWorldTeleport in the plotme config.

**Comment by xAcrosonicx** [comment]
I turned it from true to false, and now when I'm in the prison world it says "This is not a plotworld" when I do /plot home

**Comment by MattBDev** [comment]
set it back to true. Wait for 0.17 when I redo that command. ETA on 0.17 is mid April

**Comment by xAcrosonicx** [comment]
Dang. Will do, thanks
