### ISSUE TITLE
Biome Change Not working 

### ISSUE THREAD

**Issue by antondubek** [WorldCretornica/PlotMe-Core#242]
When issuing the command /plotme biome [insert biome]   nothing happens. It charges the user to use the command stating that it has changed the biome but nothing changes in game.

Any suggestions? Guessing this is a bug

**Comment by MattBDev** [comment]
Due to a bug in minecraft itself, we cannot update the color of the biome. If we did, the user would get a memory leak.
Once mojang patches this bug, I will re-add this but for the time being you need to relog.
