### ISSUE TITLE
Generating a new world error

### ISSUE THREAD

**Issue by walman1123** [WorldCretornica/PlotMe-Core#243]
Hello When i try to create a new world i get the error saying that it "Failed". The command is do is /mv create {NAME} normal -g PlotMe-DefaultGenerator. Please help me!

**Comment by MattBDev** [comment]
This is not a bug and many people have asked the same thing as you. Look in the closed issues next time. When you use the command, assuming you did not change the default world name in the configs, you would be using this command "/mv create plotworld normal -g PlotMe-DefaultGenerator". 
Also, saying "Please help me" doesn't get you help any faster.
