### ISSUE TITLE
Unable to use commands

### ISSUE THREAD

**Issue by sabrewolf** [WorldCretornica/PlotMe-Core#246]
For some strange reason, using this plugin on a 1.7.10 Cauldron server (git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212)  at some random stage, without any errors disables the command "plotme X".
There are no errors going along with attempting to use, for example "plotme home" but in the console plotme reload is able to be used.

I'm unsure if this is just a bug with Cauldron and PlotMe.

Unable to retrieve any errors from plotme.

Sorry if there is not enough to help out here.

Thanks in advance!

**Comment by sabrewolf** [comment]
Here's an interesting error i found:
http://hastebin.com/osuyoqitav.rb

**Comment by MattBDev** [comment]
Unfortunately Cauldron is not supported anymore due to the DMCA takedown and the many bugs affecting it. Your PlotMe is out of date by two versions. Try upgrading and seeing if it fixes it. I can't offer much help besides that. Appologies.
