### ISSUE TITLE
normal minecraft terrain

### ISSUE THREAD

**Issue by loopsylala99** [WorldCretornica/PlotMe-Core#253]
I made a server recently and used the command /mv create {NAME} normal -g PlotMe-DefaultGenerator with multiverse to create a plot world but the world has normal minecraft terrain and not plots.I tried using the bukkit.yml settings too to create the plots but it didnt work. please help! :(

**Comment by MattBDev** [comment]
Watch this video. This is not a bug and should not be reported here.
https://www.youtube.com/watch?v=c74550Zlp84&feature=youtu.be
