### ISSUE TITLE
Players can break other's plots

### ISSUE THREAD

**Issue by TehGreekGamerJIM** [WorldCretornica/PlotMe-Core#254]
Hello other players can brake to others plot using hand I use plot me version of 0.13f and spigot 1.7.2 R02 I have some custom plugins and I dont know if it is plotme's issue or something else there are no errors in console btw

**Comment by MattBDev** [comment]
Your version has been unsupported since December 2014. This is not the place to report bugs for this version. Please only report bugs if you are using the newest version of the plugin with a release of CraftBukkit or Spigot greater than 1.7.9

**Comment by TehGreekGamerJIM** [comment]
I updated to the newest version but still they can break and not build in others the message it appears its You cant build here when breaking and placing

**Comment by TehGreekGamerJIM** [comment]
Never mind I found the issue thanks anyways
