### ISSUE TITLE
API question

### ISSUE THREAD

**Issue by danieltabrizian** [WorldCretornica/PlotMe-Core#255]
Hey, cool stuff you got there with plotme.
but i got 1 question about the api, how can i get the outer coordinates of the plot so i can detect if the clicked block from interactevent is inside of the plot and how to i check if the plot they clicked is owned by them?

Can you please answer ASAP.

**Comment by MattBDev** [comment]
Please look at the BukkitPlotListener class to find out the answers to these questions and use ticket #237  for all future api concerns.
