### ISSUE TITLE
[Plotme] New Feature request ! Copy plot !

### ISSUE THREAD

**Issue by conetopia** [WorldCretornica/PlotMe-Core#256]
R: v0.13f for CB 1.7.9-R0.2 May 02, 2014
Using this version of the plugin for my 1.7.10 cauldron server.
Trying to figure out if there is a way for me *The owner * to copy a plot.
like Is there like plot/item logs somewhere that i could copy/paste and change a name?
is there an in-game command to simply copy someones plot?
Lets say im an admin with no plot, is there a command to claim another players plot?

**Comment by MattBDev** [comment]
0.13f and Cauldron servers are no longer supported due to compatibility issues and the DMCA takedown

**Comment by conetopia** [comment]
it works just fine on cauldron as a plugin, Im just wondering if there is a command or something for it.

**Comment by MattBDev** [comment]
No.
