### ISSUE TITLE
WorldEdit on denied/removed plots

### ISSUE THREAD

**Issue by SecretlyJealous** [WorldCretornica/PlotMe-Core#258]
If a player has set a region for worldedit on a plot they are added to and are then denied or removed they are still able to use worldedit commands on that plot. This allows people to easily grief.

**Comment by MattBDev** [comment]
Known issue. Should be fixed in 0.17 but I have yet to test it.

**Comment by MattBDev** [comment]
Fixed for 0.17
Some of the fixes are included in c1c2c1e271cc03ab6a91697094a4e611490536b9
