### ISSUE TITLE
Change a plot wall option

### ISSUE THREAD

**Issue by DaTarn** [WorldCretornica/PlotMe-Core#259]
Idea: Be able to change the wall of your own plot with the following command. (The blocks under slab boarder)
 
/plotme wall "Block ID"

- When the plot is cleared or reset, the wall is also reset to default.
- Be able to black list blocks (for example portals, heads, anvils, etc as they can create lag in large amounts) 
- Control over a cool down option to prevent over use.

**Comment by MattBDev** [comment]
Duplicate of issue #166
