### ISSUE TITLE
Plot ban/deny

### ISSUE THREAD

**Issue by DaTarn** [WorldCretornica/PlotMe-Core#260]
Idea: When you deny a player access to view your plot, they are unable to walk over the plot. What if you want to block them from seeing your content (using the blindness effect). They would receive blindness effect if they are trying to enter the plot when they are banned/denied and the effect is removed instantly when turning away and walking away.
This could be done by /plot ban [player] or be added to the /plot deny [player] function

**Comment by jomo** [comment]
I doubt this would be used a lot, so adding it to the core might be the wrong approach.
You could use the PlotMe API.

**Comment by MattBDev** [comment]
I don't feel this should be added to the main project. I agree with @jomo that it would be better suited as an add-on.
