### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by DerpShadow152** [WorldCretornica/PlotMe-Core#263]
So, I used /mv create plotworld normal -g PlotMe-DefaultGenerator to generate my world and it generated fine. When I tped to the world and I try to do /plotme for all the commands, it says "An internal error has occurred while attempting to perform this command." Im not sure if this is a bug or if I am doing something wrong. I'm running spiggot 1.8.3.

**Comment by EvilOlaf** [comment]
Console output?

**Comment by DerpShadow152** [comment]
http://pastebin.com/YF4TDmXQ
