### ISSUE TITLE
World creation with UltimateCore doesn't work

### ISSUE THREAD

**Issue by Bammerbom** [WorldCretornica/PlotMe-Core#264]
Spigot/bukkit version: 1.8.3
PlotMe version: PlotMe 0.17-172, PlotMe-DefaultGenerator 0.17
PlotMe configuration: 100% default
Startup log: http://pastebin.com/dGNVmiSX
Issue 1: http://pastebin.com/Ka3G2xNp
Issue 2: http://pastebin.com/ZE2xcT6a

Hello!

I was trying to create a new plotme world with my own plugin, UltimateCore.
But the PlotMe DefaultGenerator doesnt seem to work. 
Issue 1 (see above) is an error of PlotMe DefaultGenerator when I start my server.
Issue 2 (see above) is the error I get when I use the command /world create PlotMe normal g:PlotMe-DefaultGenerator

**Comment by EvilOlaf** [comment]
You should not use a dev build unless you know what you are doing and someone told you to do so. The are quite unstable.
Try to use latest official and see of the error still occurs.

**Comment by Bammerbom** [comment]
Now using:
PlotMe 0.16.3
PlotMe-DefaultGenerator 0.16.1

Same problem.

**Comment by MattBDev** [comment]
I have no idea what "UltimateCore" is

**Comment by MattBDev** [comment]
NEVER USE A DEV BUILD. I took down all the links to the dev builds for a reason -.-

**Comment by MattBDev** [comment]
Use a lowercase worldname instead of a name with an uppercase letter when creating a world. "Plotme" should be "plotme"

**Comment by MattBDev** [comment]
Also, if you never touched the configs, of course that command wouldn't work since you are told to modify the worldname in the configs if you don't want to use the default worldname of "plotworld"
