### ISSUE TITLE
Upgrading from Regular to Bungee

### ISSUE THREAD

**Issue by GoldenOrange** [WorldCretornica/PlotMe-Core#265]
So I changed my regular creative server over to a network. I set Bungee to online and Creative to offline. Players are not able to access their plots now. I assume it is something to do with the UUIDs. Pleas help!

**Comment by MattBDev** [comment]
I don't use bungee. Just make sure that you have it so players are being authenticated with Mojang servers. It is whatever setting bungee uses to connect to servers. I would suggest using the forums to get help if you need more help with this
