### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by tinlonchiu** [WorldCretornica/PlotMe-Core#267]
I think the developers might remember me from my last post, but now, the SQL database is haveing a problem... PlotMe is running perfectly thanks to you guys... Now I just need to know how to fix the SQL error I am seeing on my server. Just saying, I am using a MAC, and I can't read log files that good(newb at this)
Spigot 1.7.10
Plotme 0.16.3
Pastebin http://pastebin.com/BCHAVAhM

**Comment by MattBDev** [comment]
Your server is running way too slow if this is happening. You can disable metrics in the metrics folder located inside your plugins folder but I doubt it would help. You also have many broken plugins that are either corrupted or meant for 1.8+ . I once again encourage you to upgrade to Spigot 1.8.3

**Comment by tinlonchiu** [comment]
There is still a reason why I haven't upgraded to 1.8.3 and that's because my other plugins haven't upgraded to 1.8? Do you know any other way? Do I need more RAM(8GB)? Thanks for your help though

**Comment by MattBDev** [comment]
What plugins haven't updated yet? Whatever they are, they are about 7 months too late.

**Comment by tinlonchiu** [comment]
Thanks MattB! The problem was actually the other plugins and the Metrics. Thanks
