### ISSUE TITLE
Plotme Invalid Generator Error

### ISSUE THREAD

**Issue by NightRiider** [WorldCretornica/PlotMe-Core#271]
Regarding this ticket becuase you closed it when you found the solution yet it didn't work for me:
https://github.com/WorldCretornica/PlotMe-Core/issues/270#event-290384861
I tried to rename the PlotMe-Core.jar plotme.jar and restarted the server and I still got the error message and it still doesn't work.

**Comment by MattBDev** [comment]
Don't open a new ticket if I closed the old one. It is possible to reopen tickets. As for this issue, you need to take it up with Spigot because I can't do anything at the moment.
