### ISSUE TITLE
Server help

### ISSUE THREAD

**Issue by zachcronin63** [WorldCretornica/PlotMe-Core#272]
I currently own a minecraft server an I was wondering if having 2 plot worlds is possible, please let me know how i can do this, I want one survival plot world and one creative world! Thank you

**Comment by MattBDev** [comment]
It is possible. It is not hard to setup but this is __*NOT*__ the place for asking for server help, use the spigot forums next time. All you need to do is copy and paste the current world data in each config file and create the world like you did with the first world. If you need more details, use the forums. Locking issue.
