### ISSUE TITLE
PlotMe Default Gen Failing to create world Properly

### ISSUE THREAD

**Issue by CORECAGE** [WorldCretornica/PlotMe-Core#278]
I am using 0.16.3 with Multiverse 2.5 inclusing Multiverse Portals, and Multiverse SignPortals, I am having troubles creating a new world, For PlotMe with the Default Gen using the command /mv create {NAME} normal -g PlotMe-DefaultGenerator. "http://pastebin.com/4uYbK5MQ" Is my most recent log file. Here is the Multiverse-Core Worlds.yml "http://pastebin.com/bLSwEKRK" and the Multiverse Core Config has not been altered. Here is the PlotMe Config.yml "http://pastebin.com/PQPPXpuN" My list of Plugins consist of, 
AZRank-1.2.5: 
ChestShop 3.8.1: 
Citizens v2.0.14-SNAPSHOT (build 1195): 
ClearLag v2.7.7: 
CreativeGates 2.7.5:
dynmap-2.2-aplha-1: 
DynmapPlotMe (Latest): 
Essentials2.x: 
EssentialsAntiBuild 2.x: 
EssentialsChat 2.x:
EssentialsGeoIP 2.x:
EssentialsProtect 2.x: 
EssentialsSpawn 2.x:
EssentialsXMPP 2.x:
HolographicDisplays v2.1.9:
Lockette
MassiveCore
Multivers-Core
Multiverse-Portals
Multiverse-SignPortals
PermissionsEx
PlotMe-Core
Plotme-DefaultGenerator
Prison 2
Vault
WarpSigns
Worldedit-bukkit-6.0
Worldguard-6.0.0-beta-05

I have tried deleting everything consiting of PlotMe reloaded the server Stopped it again, reinstated PlotMe, and tried again, but nothing seems to budge, I saw in the configs that something is saying "null" but I dont know much of what its pointing to, I appreciate all the help that you can give.

I apologize for any interruptions I have caused, and thanks.

**Comment by CORECAGE** [comment]
http://pastebin.com/e3JD8cpW Plotme-DefaultGenerator Config.yml

**Comment by EvilOlaf** [comment]
Use `/mv create plotworld normal -g PlotMe-DefaultGenerator` instead of `/mv create PrisonPlotMe normal -g PlotMe-DefaultGenerator`

Or rename the world "plotworld" in your config files. Use lowercase characters only. Otherwise it might not work.

**Comment by CORECAGE** [comment]
So you cant have more than one PlotWorld?

**Comment by MattBDev** [comment]
If you are trying to create a second plotworld without a second world defined in your config files, it will obviously not work.
Invalid report
