### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by hamsterfat** [WorldCretornica/PlotMe-Core#282]
this is a bug so far i found out some
1st when doing /p auto it says internal error
2nd some chunks are not loading properly only happens on plotworld but on normal world it works properly
here is the log
20.05 20:52:11 [Server] INFO at net.minecraft.server.v1_8_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:118) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:11 [Server] INFO at net.minecraft.server.v1_8_R2.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:150) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:11 [Server] INFO Caused by: net.minecraft.server.v1_8_R2.ReportedException: Exception generating new chunk
20.05 20:52:11 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
20.05 20:52:11 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:11 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:11 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:11 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:11 [Server] INFO at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:61) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:11 [Server] INFO at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_40]
20.05 20:52:11 [Server] INFO at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_40]
20.05 20:52:11 [Server] INFO java.util.concurrent.ExecutionException: net.minecraft.server.v1_8_R2.ReportedException: Exception generating new chunk
20.05 20:52:11 [Server] INFO [20:52:11 FATAL]: Error executing task
20.05 20:52:11 [Server] INFO [20:52:11 INFO]: Negative index in crash report handler (0/19)
20.05 20:52:11 [Server] INFO Caused by: java.lang.NullPointerException
20.05 20:52:11 [Server] INFO ... 5 more
20.05 20:52:11 [Server] INFO at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:11 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_40]
20.05 20:52:11 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_40]
20.05 20:52:11 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:11 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:11 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInFlying.a(SourceFile:126) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:11 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:459) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:11 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerList.d(PlayerList.java:336) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:11 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerChunkMap.movePlayer(PlayerChunkMap.java:249) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:11 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerChunkMap.b(PlayerChunkMap.java:172) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:11 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerChunkMap.a(PlayerChunkMap.java:93) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:11 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerChunkMap$PlayerChunk.<init>(PlayerChunkMap.java:337) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:11 [Server] INFO at net.minecraft.server.v1_8_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:118) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:11 [Server] INFO at net.minecraft.server.v1_8_R2.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:150) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:11 [Multicraft] Skipped 1101 lines due to rate limit (30/s)
20.05 20:52:10 [Server] INFO java.util.concurrent.ExecutionException: net.minecraft.server.v1_8_R2.ReportedException: Exception generating new chunk
20.05 20:52:10 [Server] INFO [20:52:10 FATAL]: Error executing task
20.05 20:52:10 [Server] INFO [20:52:10 INFO]: Negative index in crash report handler (0/19)
20.05 20:52:10 [Server] INFO Caused by: java.lang.NullPointerException
20.05 20:52:10 [Server] INFO ... 5 more
20.05 20:52:10 [Server] INFO at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:10 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_40]
20.05 20:52:10 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_40]
20.05 20:52:10 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:10 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:10 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInFlying.a(SourceFile:126) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:10 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:459) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:10 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerList.d(PlayerList.java:336) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:10 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerChunkMap.movePlayer(PlayerChunkMap.java:249) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:10 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerChunkMap.b(PlayerChunkMap.java:172) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:10 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerChunkMap.a(PlayerChunkMap.java:93) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:10 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerChunkMap$PlayerChunk.<init>(PlayerChunkMap.java:337) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:10 [Server] INFO at net.minecraft.server.v1_8_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:118) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:10 [Server] INFO at net.minecraft.server.v1_8_R2.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:150) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:10 [Server] INFO Caused by: net.minecraft.server.v1_8_R2.ReportedException: Exception generating new chunk
20.05 20:52:10 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
20.05 20:52:10 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:10 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:10 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:10 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:10 [Server] INFO at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:61) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:10 [Server] INFO at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_40]
20.05 20:52:10 [Server] INFO at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_40]
20.05 20:52:10 [Server] INFO java.util.concurrent.ExecutionException: net.minecraft.server.v1_8_R2.ReportedException: Exception generating new chunk
20.05 20:52:10 [Server] INFO [20:52:10 FATAL]: Error executing task
20.05 20:52:10 [Multicraft] Skipped 1063 lines due to rate limit (30/s)
20.05 20:52:09 [Server] INFO [20:52:09 FATAL]: Error executing task
20.05 20:52:09 [Server] INFO [20:52:09 INFO]: Negative index in crash report handler (0/19)
20.05 20:52:09 [Server] INFO Caused by: java.lang.NullPointerException
20.05 20:52:09 [Server] INFO ... 5 more
20.05 20:52:09 [Server] INFO at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:09 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_40]
20.05 20:52:09 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_40]
20.05 20:52:09 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:09 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInFlying$PacketPlayInLook.a(SourceFile:88) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:09 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInFlying.a(SourceFile:126) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:09 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:459) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:09 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerList.d(PlayerList.java:336) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:09 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerChunkMap.movePlayer(PlayerChunkMap.java:249) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:09 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerChunkMap.b(PlayerChunkMap.java:172) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:09 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerChunkMap.a(PlayerChunkMap.java:93) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:09 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerChunkMap$PlayerChunk.<init>(PlayerChunkMap.java:337) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:09 [Server] INFO at net.minecraft.server.v1_8_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:118) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:09 [Server] INFO at net.minecraft.server.v1_8_R2.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:150) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:09 [Server] INFO Caused by: net.minecraft.server.v1_8_R2.ReportedException: Exception generating new chunk
20.05 20:52:09 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
20.05 20:52:09 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:09 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:09 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:09 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:09 [Server] INFO at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:61) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:09 [Server] INFO at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_40]
20.05 20:52:09 [Server] INFO at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_40]
20.05 20:52:09 [Server] INFO java.util.concurrent.ExecutionException: net.minecraft.server.v1_8_R2.ReportedException: Exception generating new chunk
20.05 20:52:09 [Server] INFO [20:52:09 FATAL]: Error executing task
20.05 20:52:09 [Server] INFO [20:52:09 INFO]: Negative index in crash report handler (0/19)
20.05 20:52:09 [Multicraft] Skipped 1090 lines due to rate limit (30/s)
20.05 20:52:08 [Server] INFO [20:52:08 FATAL]: Error executing task
20.05 20:52:08 [Server] INFO [20:52:08 INFO]: Negative index in crash report handler (0/19)
20.05 20:52:08 [Server] INFO Caused by: java.lang.NullPointerException
20.05 20:52:08 [Server] INFO ... 5 more
20.05 20:52:08 [Server] INFO at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:08 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_40]
20.05 20:52:08 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_40]
20.05 20:52:08 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:08 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInFlying.a(SourceFile:8) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:08 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInFlying.a(SourceFile:126) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:08 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:459) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:08 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerList.d(PlayerList.java:336) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:08 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerChunkMap.movePlayer(PlayerChunkMap.java:249) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:08 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerChunkMap.b(PlayerChunkMap.java:172) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:08 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerChunkMap.a(PlayerChunkMap.java:93) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:08 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerChunkMap$PlayerChunk.<init>(PlayerChunkMap.java:337) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:08 [Server] INFO at net.minecraft.server.v1_8_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:118) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:08 [Server] INFO at net.minecraft.server.v1_8_R2.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:150) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:08 [Server] INFO Caused by: net.minecraft.server.v1_8_R2.ReportedException: Exception generating new chunk
20.05 20:52:08 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
20.05 20:52:08 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:08 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:08 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:08 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:08 [Server] INFO at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:61) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
20.05 20:52:08 [Server] INFO at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_40]
20.05 20:52:08 [Server] INFO at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_40]

that and it keeps spamming  cant get it correctly! the later version is working fine but when i updated to latest it fails to work

**Comment by MattBDev** [comment]
For god's sake, don't copy and paste the log! Use Pastebin.com or Hastebin.com instead. I don't want to read this unformatted crap.

**Comment by MattBDev** [comment]
This is not a plotme issue and you did not provide anything I asked for in the submitting guidelines. Next time follow the instructions. :angry:

**Comment by hamsterfat** [comment]
then your a bitch its your problem your plugin sucks plotsquared is better this is an old shit crap
when i deleted the plugin it fixes the prob are you idiot?

**Comment by MattBDev** [comment]
No. You are clearly the idiot since you are not using proper grammar and ignored the submitting guidelines. Nothing in that unformatted log mentioned code from Plotme. If you want to use a complete ripoff of this plugin then fine.
