### ISSUE TITLE
Error when generating plot world.

### ISSUE THREAD

**Issue by OneBarRouter** [WorldCretornica/PlotMe-Core#283]
Hello,

Every time I try to generate a plot world for a creative server, it says "starting creation of <WorldName>" then it just says "failed". Here is what I am typing in the command: /mv create {NAME} normal -g PlotMe-DefaultGenerator

Please help,
OneBarRouter

**Comment by OneBarRouter** [comment]
Here are my logs relating to this:
20.05 17:33:13 [Server] INFO Item Merge Radius: 2.5
20.05 17:33:13 [Server] INFO Item Despawn Rate: 6000
20.05 17:33:13 [Server] INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
20.05 17:33:13 [Server] INFO Max TNT Explosions: 100
20.05 17:33:13 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
20.05 17:33:13 [Server] INFO Max Entity Collisions: 8
20.05 17:33:13 [Server] INFO Sending up to 10 chunks per packet
20.05 17:33:13 [Server] INFO Structure Info Saving: true
20.05 17:33:13 [Server] INFO Random Lighting Updates: false
20.05 17:33:13 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
20.05 17:33:13 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
20.05 17:33:13 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
20.05 17:33:13 [Server] INFO Wheat Growth Modifier: 100%
20.05 17:33:13 [Server] INFO Sapling Growth Modifier: 100%
20.05 17:33:13 [Server] INFO Pumpkin Growth Modifier: 100%
20.05 17:33:13 [Server] INFO Mushroom Growth Modifier: 100%
20.05 17:33:13 [Server] INFO Melon Growth Modifier: 100%
20.05 17:33:13 [Server] INFO Cane Growth Modifier: 100%
20.05 17:33:13 [Server] INFO Cactus Growth Modifier: 100%
20.05 17:33:13 [Server] INFO Nerfing mobs spawned from spawners: false
20.05 17:33:13 [Server] INFO Replace Blocks: [1, 5]
20.05 17:33:13 [Server] INFO Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
20.05 17:33:13 [Server] INFO Engine Mode: 1
20.05 17:33:13 [Server] INFO Anti X-Ray: true
20.05 17:33:13 [Server] INFO Mob Spawn Range: 4
20.05 17:33:13 [Server] INFO -------- World Settings For [yolo420] --------
20.05 17:33:13 [Server] INFO Loading World & Settings - 'yolo420' - Env: NORMAL - Type: NORMAL & generator: PlotMe-DefaultGenerator
20.05 17:33:13 [Server] INFO O8THEUNKNOWN8O: Starting creation of world 'yolo420'...

**Comment by MattBDev** [comment]
Please don't report issues if you are not going to follow the guide to submitting. Your issue is a duplicate and you should try to follow the setup video on our website.
