### ISSUE TITLE
remove expiration from a plot

### ISSUE THREAD

**Issue by cicatrice74** [WorldCretornica/PlotMe-Core#284]
Can u please add an option to remove expiration from a single plot?

**Comment by MattBDev** [comment]
Any reason you need this? Protecting a plot should ignore expired plots if you are resetting expired plots. Plus you should be able to just place a block on the plot to update the expiration date.

**Comment by cicatrice74** [comment]
Need this cause i used 4 plots around the plotme world's spawn to create a
bigger spawn and i need those plots to not expire do u know a way to do
this?
Il 24/Mag/2015 04:28, "Matt" <notifications@github.com> ha scritto:

**Comment by MattBDev** [comment]
You protect the plots. Do you understand what an expiration does to the plot?

**Comment by MattBDev** [comment]
@cicatrice74 Are you still there? This ticket will be closed if you do not respond in 24 hours

**Comment by cicatrice74** [comment]
I already protected those plots but i really don't know what expiration do;
can u finally complete explain me that and how to protect from the command
to reset expired plots? Tnx
Il 26/Mag/2015 06:06, "Matt" <notifications@github.com> ha scritto:

**Comment by MattBDev** [comment]
If you use "/plot protect" the plots are safe from any resets, clears, disposal, and (in the next version) movement. This means that when you mark a plot as protected, the expiration date does nothing. It is just a meaningless date. Using the reset expired command will not get rid of the plot as long as it is protected.
Does this make sense to you? Do you still think I need to allow the ability to remove expirations? Let me know so I can resolve this ticket.

**Comment by cicatrice74** [comment]
I think its sufficient for me but i still think you could remove the
expiration date info from protected plots so no mistakes...u can replace
with expiration:disabled...ok with this i think u can close the ticket
sorry for noob questions thank you very much for spending your time for
this.
Il 26/Mag/2015 06:36, "Matt" <notifications@github.com> ha scritto:

**Comment by MattBDev** [comment]
I just took a look that the plot info format and made adjustments based off your feedback. I'm happy I was able to help. :smile:
