### ISSUE TITLE
NullPointerException when attempting to create a new default world

### ISSUE THREAD

**Issue by stefan15ist** [WorldCretornica/PlotMe-Core#285]
I have the world in the bukkit.yml and then I want it to create a new world using the latest version of the PlotMe plugin and this exception occurs:
http://hastebin.com/iducahatic.avrasm

**Comment by MattBDev** [comment]
Read the instructions, read the troubleshooting, and don't report a bug that has been reported before. You didn't even follow the bug reporting guidelines! :-1:
