### ISSUE TITLE
Players cannot build or break blocks

### ISSUE THREAD

**Issue by Athe97** [WorldCretornica/PlotMe-Core#287]
Sorry I didn't see that there was a format!
Version:
Bukkit: R22A
Plotme version: 0.16.1
Config: http://pastebin.com/ttCPydn3
Config 2 : http://pastebin.com/6nSWbyiB
Latest logs: http://pastebin.com/EuLr7dN4
What I did to make this issue occure: Nothing. I installed the plugin, loaded it up and couldn't build.

Ps:
I've been searching for several hours now but have yet to find a solution. Players can own a plot, but cannot build nor break blocks. The spawn-protection is set to 0 and all config are left untouched. I have group manager aswell and default build was set to true.
I've tried deleting all regions in the plotworld but with no success. I have also set the world and generator in the bukkit.yml. Basically i've done everything that was suggested in the other threads. I have WorldGuard, Essentials, Group Manager and Multiverse (Atleast those are the plugins i'd suspect are linked to PlotMe)This is a great plugin and I don't want to look for another. If you guys could help me out i'd appreciate it greatly!

**Comment by MattBDev** [comment]
World guard is a possible conflict. Please try disabling  it for plotworld and let me know if it fixes it

**Comment by Athe97** [comment]
I've tried disabling World Guard but no luck.

**Comment by MattBDev** [comment]
I'll be able to help more later tonight if Markus doesn't see that he is assigned to help you. Right now I am on my phone.

**Comment by Athe97** [comment]
Alright thank you :)

**Comment by Athe97** [comment]
Edit: I just discovered that defaults cannot build or break anywhere in the other worlds. They have all the permission nodes but whenever they try to build/break blocks, they respawn. No message or anything.

**Comment by MattBDev** [comment]
Can you tell me what the plugin "BukkitCompat" is? I see it in your log file and you listed that plugin's version as your Bukkit Version. I am not sure what it is or does.

**Comment by MattBDev** [comment]
@Athe97 Ping. If you don't reply I will have to close this ticket.

**Comment by MattBDev** [comment]
Closed due to no response
