### ISSUE TITLE
Plots messed up!

### ISSUE THREAD

**Issue by xAcrosonicx** [WorldCretornica/PlotMe-Core#288]
Hello, I just updated to 1.8 and I have two plot worlds. One for massive plots, and one for normal. When I updated, I also updated to the latest version of PlotMe, and it messed with my large plot world.  Here's the config, creative is the big plots that are messed up. http://pastebin.com/ePXv397c

**Comment by MattBDev** [comment]
If the following details are not provided within 9 hours of this posting, the ticket will be closed. The following is needed:
* Screenshots
* A better description of the issue
* Your PlotMe Config file **AND** your default generator config
* Your server's latest.log file
Please use pastebin to provide the text files needed. A link to the pictures on a service like imgur, dropbox, onedrive, or google drive will work.

**Comment by xAcrosonicx** [comment]
Issue: I updated my server jar to 1.8, and installed the latest version of PlotMe. Ever since then, one of my plotworlds (named creative) is messed up. The plots seem to be shifted over a few blocks into the road, meaning a few blocks on the opposite side of the plot thinks it's the road. 

Screenshots: http://i.imgur.com/RVWzjUx.png (You'll notice I'm standing on a plot, did plot info, and it said no plot found.) 
                     http://i.imgur.com/1J7ZTyO.png (This one you'll see even more blocks over, still no plot)
                     http://i.imgur.com/mtj6qD2.png  (Now the middle of the road thinks it's the plot)

Latest.log:    http://pastebin.com/euBFGkYC

Config.yml:   http://pastebin.com/MkuNaHd0

DefaultGenerator: http://pastebin.com/60RL9snV  (I never touched this, and am unsure why there are two different "creatives"

**Comment by EvilOlaf** [comment]
World names have to be written in lowercase in order to work properly.

**Comment by MattBDev** [comment]
Did not read setup/upgrade instructions.

**Comment by xAcrosonicx** [comment]
So how am I suppose to fix this? Players plots are all messed up.

**Comment by MattBDev** [comment]
First, read the comment @EvilOlaf said. Second, read the upgrade instructions and delete the duplicate world from the config.
