### ISSUE TITLE
Wat? Itemframes and Armour stands aren't protected?

### ISSUE THREAD

**Issue by YepImRobbie** [WorldCretornica/PlotMe-Core#289]
Isn't failing to protect item frames and armour stands undermining the purpose of having a protected plot? :(

I have a creative world-edit server, the world-edit is constantly knocking out the item frames and they become missing in the frame-protect database, it's extremely annoying. I don't want frame-protect anymore.

Add automatic item-frame+painting and armour-stand protection on plots.

**Comment by MattBDev** [comment]
You have failed to follow the bug submitting guidelines so this report will be closed unless you follow up with the details requested for submitting. Also, item frames are protected but armor stands are not due to a technical limitation that would break backwards compatibility.

**Comment by YepImRobbie** [comment]
So sorry, thank you so much, I can now get rid of frameprotect, such an awful plugin with limited customisability, sorry matt.
