### ISSUE TITLE
Players can't use Flint and Steel on plots.

### ISSUE THREAD

**Issue by BotQq** [WorldCretornica/PlotMe-Core#293]
Hello. Players can't use fire on their plots. I use Spigot 1.7.10(#1649) and PlotMe v.0.16.3.
My config: http://pastebin.com/Z01A2YU4

**Comment by MattBDev** [comment]
Please provide the details required by the bug submitting format which can be found [here](http://plotme.worldcretornica.com/issues.html).
If the details are not provided in 24 hours, this report will be closed.

**Comment by BotQq** [comment]
What can i add? log file?;_; Ok,i'll explain you my issue. Players craft flint and steel. Then they place blocks,for example netherrack on their plots. After that they try to set on fire on it using lighter. Unfortunately,they can't.

**Comment by EvilOlaf** [comment]
Stated above: http://plotme.worldcretornica.com/issues.html

As I quote:
```
Spigot/Bukkit version
PlotMe Version (Saying "Latest" or "Newest" does not help. You can use /version PlotMe to find the version number.)
A pastebin/hastebin of all your PlotMe configuration files
A copy of your latest.log file (hastebin/pastebin these)
What did you do in order for the issue to occurs
```

**Comment by MattBDev** [comment]
I would also like to note that 1.7.10 servers will not be supported in the future. My guess is that you have a different plugin modifying this behavior.

**Comment by MattBDev** [comment]
Closed because user never followed up on this conversation
