### ISSUE TITLE
Disabling plotme expiration date

### ISSUE THREAD

**Issue by YepImRobbie** [WorldCretornica/PlotMe-Core#294]
Hi,

Where is the setting to whereby I can disable the expiry date, it scares my players to death although to what I believe it's meaningless.

How do I make plots infinite and never expire.

**Comment by MattBDev** [comment]
This is not a bug. Please do us this to ask questions. Use the spigot forums instead. Just set the date to 0. It isn't that complicated. -.-

**Comment by YepImRobbie** [comment]
Thanks. :)
