### ISSUE TITLE
ConcurrentModificationException when many player log in at once

### ISSUE THREAD

**Issue by minoneer** [WorldCretornica/PlotMe-Core#295]
Hey,

whenever several players log in "at once" (within a short amount of time) like after a server restart or when a few players had a time out, PlotMe causes ConcurrentModificationExceptions (see pastebin below).

Server version: CraftBukkit version git-Spigot-1d14d5f-ba32592 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
PlotMe version: 0.16.3
Logs: http://pastebin.com/yED7GRYP

By looking through the code, I'm assuming it is because the task in PlotMeCoreManager#UpdatePlayerNameFromId(UUID, String) is executed asynchronously, without synchronizing the PlayerList and therefore instantiating multiple iterators on the same map concurrently.

Regards, minoneer

**Comment by MattBDev** [comment]
Thanks so much for the report. Although I have removed `PlayerList` in 0.17 this will be super helpful for me when finalizing the data caching system.

**Comment by MattBDev** [comment]
As far as I am aware, this should be fixed in the newest dev release.

**Comment by minoneer** [comment]
Which build exactly is that?

**Comment by MattBDev** [comment]
Whatever the newest build is. It is not fully functioning though. Somewhere between 175 and 200
