### ISSUE TITLE
Plotme players can break but not place blocks

### ISSUE THREAD

**Issue by TehGreekGamerJIM** [WorldCretornica/PlotMe-Core#296]
Spigot jar version 1.7.10 SNAPSHO
Plotme version 0.13b
Config1: http://pastebin.com/UwYabp2L
Unfortunately I cannot upload a pastebin or hastebin cause there as 155k lines Here is a dropbox of the latest logs https://www.dropbox.com/s/xorx8vzm6qxzodz/latest.log?dl=0
What did you do in order for the issue to occur? Nothing

**Comment by MattBDev** [comment]
PlotMe 0.13b is no longer supported.
