### ISSUE TITLE
How to update PlotMe

### ISSUE THREAD

**Issue by TehGreekGamerJIM** [WorldCretornica/PlotMe-Core#297]
Hello I am using an unsupported version of PlotMe on my server (As I learned) I am using Spigot 1.7.10 SNAPSHOT.I would like to know how can I update it to the right one.

Do i have to keep the world and just change the plotme.jar?

**Comment by MattBDev** [comment]
Upgrade instructions are on our website. This is not the place to ask questions, this is a place to report bugs.

**Comment by TehGreekGamerJIM** [comment]
Apologies for that but I cant see a Question/Help page, there is only FAQ.In IRC there is noone responding

**Comment by MarkusAV** [comment]
@TehGreekGamerJIM  http://plotme.worldcretornica.com/issues.html
