### ISSUE TITLE
Users crashing

### ISSUE THREAD

**Issue by MrROBOT11000** [WorldCretornica/PlotMe-Core#298]
Some users are crashing when they go on their plot. They get the error message in the picture attached. They are then unable to re join the server unless they connect via Minechat using the auto spawn feature! Help!
![plotcrash](https://cloud.githubusercontent.com/assets/12858951/8128326/b7f8d30c-10f5-11e5-8d2e-8c240ba7e664.png)

**Comment by MattBDev** [comment]
This seems like more of a client issue which I have no control of since I don't modify anything within netty. If you truly believe it is a plotme issue, I will reopen this if you provide me the client logs and server logs so I can see what is happening.
