### ISSUE TITLE
Plots resetting on server reset

### ISSUE THREAD

**Issue by Trevor450** [WorldCretornica/PlotMe-Core#304]
Jar - Spigot Protocol Hack

Plotme Version -  0.16.3

Pastebin of configs - http://pastebin.com/9PDtBBfp

Latest Log - http://pastebin.com/1mW2dRV8

My issue is that when the server is restarted all of the plots are reset, but they keep their owners. 
Although it's not just the plots, the entire world resets.

Another problem is that /plotme auto says "No plot found within 3 plots. Contact an admin."
My email is trevorthornbury2@gmail.com

**Comment by MattBDev** [comment]
I cannot do much since the latest.log file was removed from pastebin. Spigot Protocol hack will not be supported in 0.17 releases so I can't really fix this for you.
