### ISSUE TITLE
Plotworld not being created

### ISSUE THREAD

**Issue by MastefChief** [WorldCretornica/PlotMe-Core#305]
I tried to create a world using this command : "/mv create Creative normal -g PlotMe-DefaultGenerator" and multiverse tells me creation failed. Is there anyway i can fix this?
![screenshot_1](https://cloud.githubusercontent.com/assets/10660965/8365676/46abb26e-1b54-11e5-87cb-66a3c5bac7e8.png)

**Comment by MattBDev** [comment]
The original poster did not provide details requested for filling out bugs nor did they look at previously closed issues.
