### ISSUE TITLE
Creative Plot Issue

### ISSUE THREAD

**Issue by VashmantieYT** [WorldCretornica/PlotMe-Core#306]
If you are outside of your creative plot and try to build or break a block inside of your plot, it will say "You cant build here". This is really annoying if you are building on the borders of your plot and cant build something that is in your plot but you cant because you are outside of it.

Please (if there is a way) fix this.

-Jacob Knight

**Comment by MattBDev** [comment]
Duplicate issue. I've already said this will be fixed in the next version due out this weekend. The title of this issue wasn't even relevant.
