### ISSUE TITLE
Plotme generator not working

### ISSUE THREAD

**Issue by zDrakon** [WorldCretornica/PlotMe-Core#307]
After flying for like 3 minutes in 1 direction you can see the wilderness. How do you fix this? I want it to be neverending.. maybe like 100,000 plots. maybe 1,000,000

**Comment by MattBDev** [comment]
If there is no error in console then it is not an issue with plotme but an issue with Bukkit/Spigot. 
In the future, please make sure to use the proper format requested for reporting an issue or your posts will be ignored.
