### ISSUE TITLE
PlotMe does not generate new plotworld...not any plotworld at all...

### ISSUE THREAD

**Issue by mjgus** [WorldCretornica/PlotMe-Core#308]
Mac, latest software and plugs (Spigot, Java, PlotMe, etc, etc), no MultiVerse or MultiWorld - vant to create ONE plotworbd - enter in buckit.yml:

worlds:
    plotworld:
        generator: PlotMe-DefaultGenerator

Nothing happens - the Spigot server just creates the original worlds (world, world-nether, world-the-end).

Regards; Jörgen Gustafson

**Comment by MattBDev** [comment]
Never setup plotme properly

**Comment by mjgus** [comment]
I got it! I had missed to set the same world name in "server.properties". So - it has to be exactly the same in 4 places in different files. It's running now :-)
