### ISSUE TITLE
A few console errors

### ISSUE THREAD

**Issue by dmulloy2** [WorldCretornica/PlotMe-Core#309]
Spigot version: git-Spigot-f928e7a-994b2aa (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)
PlotMe version: 0.17-200, latest development build.
Default configs, haven't touched them

Error when using /plot auto: http://pastebin.com/9pEcn9Af
Error when using /plot help: http://pastebin.com/WeC7SStS

Any help would be appreciated.

**Comment by MattBDev** [comment]
Thank you for the report! Fixed for official 0.17 release
