### ISSUE TITLE
Not an issue just a few questions :)

### ISSUE THREAD

**Issue by YepImRobbie** [WorldCretornica/PlotMe-Core#310]
Hey guys, love the list of new feature in 0.17 just a little bit scared upon updating.

My questions are:
1. Is SQLite the file? Like xxxxx.db
2. Do I convert plotmecore.db and plots.db or ONLY one

Thanks in advance and do you have a donation button?

**Comment by MattBDev** [comment]
1) yes.
2) you shouldn't have a plotmecore.db file, only plots.db
the donation button can be found on the spigot page.

**Comment by MattBDev** [comment]
I hope my answers helped
