### ISSUE TITLE
Beds Destroy Roads

### ISSUE THREAD

**Issue by Teg-MC** [WorldCretornica/PlotMe-Core#316]
Spigot version:
> ![Spigot version](http://i.teg.pw/omk9h.png)

PlotMe version:
> ![PlotMe version](http://i.teg.pw/n3xvl.png)

If you change a plot's biome to HELL using `/plotme biome HELL`, place a bed inside the plot (near the road) and right click the bed it will explode and destroy the road.

> ![Destruction](http://i.teg.pw/2015-07-02_15.36.41.png)

**Comment by MattBDev** [comment]
I can't reproduce this behavior on 0.17 or 0.17.1 So it is either fixed or something overrides plotme's protection
