### ISSUE TITLE
Plotme  /plotme clear

### ISSUE THREAD

**Issue by Cjroange** [WorldCretornica/PlotMe-Core#318]
Why does it spam your chat to just clear a plot. Also it takes so long to clear a plot as well.... Can this be fixed?

**Comment by MattBDev** [comment]
It takes long because it clears the plot in sections to reduce lag. It tells the people the plot is being cleared until the clear finished so people don't crash the server by doing plot clear thinking the plot isnt being cleared

**Comment by MattBDev** [comment]
It cannot be fixed until I redesign the generator

**Comment by Cjroange** [comment]
Okay. When will you fix the generator?

**Comment by MattBDev** [comment]
I am actively working on it. I need to perform some tests before I continue my work on it.
