### ISSUE TITLE
PlotMe folder not generating

### ISSUE THREAD

**Issue by nitroxplunge** [WorldCretornica/PlotMe-Core#319]
Hi! I'm creating a creative server on my server network and i'm having problems generating the PlotMe folder. Here's my log:

04.07 12:42:33 [Server] INFO org.bukkit.plugin.UnknownDependencyException: PlotMe
04.07 12:42:33 [Server] ERROR Could not load 'plugins/PlotMe-DefaultGenerator.jar' in folder 'plugins'
04.07 12:42:33 [Server] INFO ... 6 more
04.07 12:42:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
04.07 12:42:33 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.&lt;init&gt;(PluginClassLoader.java:76) ~[Spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
04.07 12:42:33 [Server] INFO at java.lang.Class.newInstance(Unknown Source) ~[?:1.7.0_72]
04.07 12:42:33 [Server] INFO at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.7.0_72]
04.07 12:42:33 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.7.0_72]
04.07 12:42:33 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.7.0_72]
04.07 12:42:33 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_72]
04.07 12:42:33 [Server] INFO at com.worldcretornica.plotme_core.bukkit.PlotMe_CorePlugin.&lt;init&gt;(PlotMe_CorePlugin.java:29) ~[?:?]
04.07 12:42:33 [Server] INFO at com.worldcretornica.plotme_core.PlotMe_Core.&lt;init&gt;(PlotMe_Core.java:30)

I'm on a time constraint for this server so i need help with this fast.
Thanks!

**Comment by MattBDev** [comment]
This is because plotme is supposed to be run before the default generator. Make sure you have both jars in your plugins folder. If it still isn't working, yell at the spigot team to fix it because I've done as much as I can to fix this.
