### ISSUE TITLE
Command /plotme doesn't work

### ISSUE THREAD

**Issue by NickFirenzo** [WorldCretornica/PlotMe-Core#320]
I have a problem concerning the PlotMe, commands from /plot does not work, use bungeecord mode, a server where the plot is spigot 1.8.2, please tell me how to fix.
Plugins: http://prntscr.com/7peh3z
When I type /plot or /plotme does not go any text says that the command does not exist.
Please tell me what should I do, thanks :)
My server is offline mode, bungeecord offline mode and spigot 1.8.2 offline mode

**Comment by divad** [comment]
What PlotMe version are you using?

Any errors on the console?

**Comment by MattBDev** [comment]
I cannot reproduce this.

**Comment by NickFirenzo** [comment]
There is no error in the console, just does not work the command /plotme and does not give any notice that the command does not exist, plugin operate normally, generates plot as normal. I use the latest version.

**Comment by divad** [comment]
To confirm, 0.17.4 ?

**Comment by NickFirenzo** [comment]
what?

**Comment by divad** [comment]
Can you confirm you are running 0.17.4.

**Comment by MattBDev** [comment]
@NickFirenzo Saying the "latest version" could mean multiple things. just say the version number.

**Comment by MarkusAV** [comment]
Hey @divad :D can i get unbanned from mineactivity? :(

**Comment by divad** [comment]
This is not the place for ban appeals on mineactivity - appeal your ban on manager.mineactivity.com

**Comment by NickFirenzo** [comment]
My problem has been solved, thanks :)
