### ISSUE TITLE
How to setup, all players can build on one plot - PrisonMine

### ISSUE THREAD

**Issue by NickFirenzo** [WorldCretornica/PlotMe-Core#326]
Hello, 
I have a problem with PlotMe I made mine, I can do RolePlay server. Now I have a problem with plots. How to setup so that all players can break a plot(mine), you can dig in the mine, as it turns out 'You can not build here'. How to fix this? Thanks a lot.
I claim a mine with worldguard(/rg define) and /rg flat build allow, but can't break.
Mine(picture): http://prntscr.com/7ou19p

**Comment by MattBDev** [comment]
you can allow players to accomplish this. this is not a bug. REPORT BUGS ONLY. Don't ask questions here.
