### ISSUE TITLE
How to setup, all players can build on one plot - PrisonMine

### ISSUE THREAD

**Issue by NickFirenzo** [WorldCretornica/PlotMe-Core#327]
Sorry for open again, but where and how setup to can break all players in PrisonMine?
Theme: https://github.com/WorldCretornica/PlotMe-Core/issues/326

**Comment by EvilOlaf** [comment]
`/plotme add *`

**Comment by NickFirenzo** [comment]
Thanks MEN A LOT!!!!!!!!!!!!!!
