### ISSUE TITLE
my plotme has stop working randomly

### ISSUE THREAD

**Issue by Dj7779** [WorldCretornica/PlotMe-Core#329]
okay, so i had my server open in putty.exe and everything was working just fine. my server stopped because my computer restart so it stop the server via putty so it stopped. When I woke up I came to see my server wasn't on so I turned it on and a bunch of plugins worn't working so i fixed it and plotme was the only plugin that wouldn't fix its self and I don't know why. Anything I can do?

**Comment by MattBDev** [comment]
Yeah you provided NOTHING that will allow me to help you. There is nothing in your post that meets the guidelines for reporting a bug.
