### ISSUE TITLE
All of plot me not working

### ISSUE THREAD

**Issue by TJM4** [WorldCretornica/PlotMe-Core#333]
Hello, thank you for taking the time to read my error.

I have run a few servers with PlotMe and it has always been an epic plugin but I am starting a new one at the moment (the server is home hosted on my computer during setup). Here is some basic information:

PlotMe version: 0.17.5-BETA
PlotMe-DefaultGenerator version: 0.17.1
When I do /version I get the following:
http://gyazo.com/d15fda9691b36fec996e8c53cc00bc10 <--- View link to see

PlotMe Configs:
PlotMe config - http://pastebin.com/LZu0PCkz
PlotMe-DefaultGenerator config - http://pastebin.com/VtW0w1GK

Extra info:

Whenever I do any commands to do with PlotMe I get 'An internal error happened' message. The error in the console is: http://pastebin.com/PHyRBE1w

I have tried to create a world but it says the generator is invalid

Thanks a lot for taking the time to read this and I hope someone can help!

- TJM4

**Comment by MattBDev** [comment]
Can you try creating the world again and showing me the console log?

**Comment by TJM4** [comment]
After re-installing the plugin and deleting the config it worked! Thank for your help anyway
