### ISSUE TITLE
Trapped Chest doesn't private

### ISSUE THREAD

**Issue by jarocajavi** [WorldCretornica/PlotMe-Core#334]
Spigot Version - 1.8.7
Plotme Version - 0.16.3
Plotme-DefaultGenerator - 0.16.1

Pastebin of all PlotMe configuration files:

 - config.yml     -    http://pastebin.com/arjHGgdk
 - captions.yml    -    http://pastebin.com/TbQzPNuz
Plotme-DefaultGenerator
config.yml    -    http://pastebin.com/T3h0kd32

Latest Log - http://pastebin.com/1GxyXmiy

The storage items privatization system (hopper, chest, furnace…) works correctly except the trapped chest.

Thanks anyway.

**Comment by EvilOlaf** [comment]
You need to add 146 to the list of protected blocks

**Comment by jarocajavi** [comment]
Sorry, im very stupid. xD
