### ISSUE TITLE
PlotMe Generation Problem

### ISSUE THREAD

**Issue by nitroxplunge** [WorldCretornica/PlotMe-Core#335]
Spigot Version: 1.8.7
PlotMe Versions:
  - PlotMe-Core v0.17.4
  - PlotMe-DefaultGenerator v0.17.1
I don't have config files yet (that's the problem!).
No log files yet.
I downloaded the PlotMe files from the portal and dragged them into my plugins folder.

Hi,

I got the PlotMe files from the website portal and put them in my plugins folder. When i run the server (or restart it!), the config files don't generate and the plugin doesn't get recognized by the server. The last reviewer that got one of these (15 days ago) said it was a spigot problem and to contact spigot. So, i did that and they said that others were using it fine and it was a problem with me. Am i doing anything wrong? And if you don't know, can you be nicer than the last reviewer and at least give me (a) suggestion(s) on what to try?

Thanks,
nitrox_plunge

**Comment by MattBDev** [comment]
If the plugin enables and doesn't shoot out any errors in the console then there is nothing I can do.

**Comment by MarkusAV** [comment]
somebody actually used the download portal :scream:
