### ISSUE TITLE
Bukkit.getWorld(world) returns null when PlotMe is installed.

### ISSUE THREAD

**Issue by woutwoot** [WorldCretornica/PlotMe-Core#336]
Hi. I have a problem with PlotMe conflicting with my plugin. 
I was hoping someone here could help me. I have a shop plugin that uses Item fames, on startup I load the shops by scanning a chunk for entities and matching the locations. 
Without plotme this is working completely fine. With plotme, for some reason, the World is null. 
(Location l = new Location(Bukkit.getWorld(world), x, y, z);)

**Comment by MattBDev** [comment]
PlotMe does not affect the way the Bukkit API works. I recommend contacting the spigot team if this is an issue.
