### ISSUE TITLE
Plotme, break blocks

### ISSUE THREAD

**Issue by NickFirenzo** [WorldCretornica/PlotMe-Core#337]
Hello, I want to report the bug about plots. The player is the owner of that plot can not run target plot. Up to half, and then half can not violate.
It happens at times or a bug?

**Comment by MattBDev** [comment]
I don't understand the report. Can you please try to describe it in more detail or possibly share a video?

**Comment by NickFirenzo** [comment]
I will post a video, wait

**Comment by MattBDev** [comment]
Still waiting for a video
