### ISSUE TITLE
Not sure whats going on?!?!

### ISSUE THREAD

**Issue by bradmyers12** [WorldCretornica/PlotMe-Core#339]
Having server crashes put not sure whats causing it. I believe it might be corrupted chunks.

Yesterday's Crash log
http://pastebin.com/wy4EbsTX

Today's Crash Log
http://pastebin.com/ShKWGd2i

**Comment by bradmyers12** [comment]
Currently using verison 0.16.3

**Comment by MattBDev** [comment]
These crash logs are of two completely different issues. Either way, they are both fixed for 0.17.5
