### ISSUE TITLE
PlotMe World Configs NOT Applying!

### ISSUE THREAD

**Issue by Galantiiss** [WorldCretornica/PlotMe-Core#347]
Here is my DefaultGenerator World Config - 
    http://pastebin.com/sU2UqM6r
Here is my PlotMe Config - 
    http://pastebin.com/QM570xKW
My Server Version Is - 
    CraftBukkit 1.8.7
My PlotMe Version Is - 
    0.17.4
My PlotMe-DefaultGenerator Version Is -
    0.17.1

Thank You !

**Comment by sammyg123** [comment]
when you run the multiverse command to generate a new world, are you using the world name you specified in the generator config?

**Comment by Galantiiss** [comment]
yes in the config it is creativeplots and the world i use in the command is
also creativeplots
