### ISSUE TITLE
Help with Installation!!!!

### ISSUE THREAD

**Issue by ironcaptain101** [WorldCretornica/PlotMe-Core#349]
I am using MCProhosting to make a server and PlotMe didn't show up with the plugins option so I manually installed it and put everything correctly but the plugin won't register!  I put both .jar's in the plugins folder.  Help!

**Comment by EvilOlaf** [comment]
Without any further information like console output there is probably no way to help you.

**Comment by MattBDev** [comment]
Closed because this user provided NO INFORMATION
