### ISSUE TITLE
Create a world with Multiworld

### ISSUE THREAD

**Issue by kiruaa** [WorldCretornica/PlotMe-Core#350]
Hello all :)
I try to run on a server in Plotme 1.7.10 (in the cauldron ) . The plugins that burden well, but can not generate a map with plotme (I use the multiworld plugins) .
I tried several commands without great success ...
( I use version 0.13b plotme there has to use a single file ? )
My PlotMe configuration files = default
I am forced to use version 0.13 is given as the server is running in offline

A little help? Thx you.

( log on create world: http://hastebin.com/raw/oqukuxakul )

**Comment by MattBDev** [comment]
1) 0.13b is not supported.
2) This is not tech support
3) I only support 1.8 servers and not cauldron.
