### ISSUE TITLE
Player cannot build within their plot while flying above a generated road

### ISSUE THREAD

**Issue by excetna** [WorldCretornica/PlotMe-Core#353]
Spigot Version: git-Spigot-c8a0d06-58d972f (MC: 1.8.7)
PlotMe Version: 0.16.3
Configs:
Captions:
http://pastebin.com/MkKr8UeA
config.yml:
http://pastebin.com/Em5J0Mjh
PlotMe-DefaultGenerator config.yml:
http://pastebin.com/uxKsYn83
latest.log:
http://pastebin.com/DEZpHJGL

Issue occurring:
A player built right next to the edge of their plot, so they hovered above the generated roads using fly mode. They noticed that they could not build while the were hovering above the road, even though they were trying to place blocks within their plot. I confirmed that they were having that problem by using another account. I did notice (as I had op) I could place blocks into their plot while I was above the road. I looked for a permission relating to the issue the player was having. However, even if there was such a permission, I still think this should be considered a bug.

P.S.: I was debating on whether to consider this a feature to be requested or a bug. I considered it a bug because, I don't see why players should be disallowed to build in their plot if they're standing outside it. But, I also think that a function was never programmed in to check if a player was standing outside a plot and trying to build within their plot. Because of that, I see how this could be seen as an additional feature request as well. 

P.S.S: I don't think you're going to find much in the latest.log besides me being a scrub at using the /plotme home command. Thanks for reviewing this bug.

**Comment by MattBDev** [comment]
Known bug. Already fixed for 0.17/5
