### ISSUE TITLE
Players cannot build on their plots if standing outside.

### ISSUE THREAD

**Issue by Foorack** [WorldCretornica/PlotMe-Core#354]
As title describes, if you are stand or flying above the road you cannot place blocks or you own plot. Sorry for the little amount of info, don't know what would be relevant to include.

Running version 0.16.1

**Comment by EvilOlaf** [comment]
Firstly you should upgrade to the most recent version of plotme and check if the issue still there.

**Comment by MattBDev** [comment]
Fixed for 0.17
