### ISSUE TITLE
Mark center of plots

### ISSUE THREAD

**Issue by Bobcat00** [WorldCretornica/PlotMe-Core#36]
Add a PlotCenterBlockId indicating a block which would be automatically placed at the center of each plot when it is generated.  There would be either 1 or 4 blocks of this ID, depending if PlotSize was odd or even.  Users could specify blocks like stone or glowstone so they can easily find the exact center of their plots.  The block could default to 2 (grass) so it would be backwards compatible with existing use.

**Comment by MarkusAV** [comment]
A command could also be ideal, such as "/plot middle" that would just tp the player to the middle.., would be easier and players could find the middle infinite times (if they removed the middle blocks)

**Comment by ZachBora** [comment]
command /plot middle added for next release
