### ISSUE TITLE
PlotMe Default Generator 1.7.2

### ISSUE THREAD

**Issue by Huardamon10** [WorldCretornica/PlotMe-Core#363]
Is it possible for me to get a download for the Bukkit 1.7.2 version of PlotMe Default Generator? I've looked on the website and haven't found it. Thanks!

**Comment by blake0201** [comment]
in 1.7 the plotme default generator is built it just do /mv create {NAME} normal -g PlotMe

**Comment by Huardamon10** [comment]
Thanks for your help! Now when I built the world and went into it and tried issuing the command /plotme claim, the server said that the world wasn't a plot world. Any suggestions on how to fix that?

**Comment by blake0201** [comment]
in the config is the name of your world matching the config name
