### ISSUE TITLE
/plot move Not working properly

### ISSUE THREAD

**Issue by Puharesource** [WorldCretornica/PlotMe-Core#43]
I've only tried this once, seeing as it lagged the server a little bit + The build that I tried to move, was destroyed.

So what happened was that I had to plots, let's call them A & B. Plot A was a claimed plot, that I wanted to move to a new location and plot B was an unclaimed plot that I wanted it to be replaced with. When I used command /plot move <coordinates for B> <coordinates for A> It lagged the server for a few seconds, after it was done moving the result was the following: The place where Plot A used to be had been replaced with pure dirt, no air JUST dirt and plot B had been replaced the same way, however, that plot was now JUST bedrock.

##### Other information: #####
WorldEdit version: `Bukkit-Official (6.0.2-SNAPSHOT;3347-fe6717a0)`
Spigot version: `git-Spigot-b43a31a-975c9ed (MC: 1.8) 1.8-R0.1-SNAPSHOT`

**Comment by MattBDev** [comment]
@ZachBora has been working on fixing this and making it more stable. The work he is doing can be found in https://github.com/WorldCretornica/PlotMe-AbstractGenerator

**Comment by ZachBora** [comment]
We have a new move system coming soon but it's not finalized yet. Still some things to be tested and a failover, in case server crashes mid-doing a move.

**Comment by Puharesource** [comment]
Sounds good :+1:
