### ISSUE TITLE
This is not a plotworld/ Internal errors when using plotme commands

### ISSUE THREAD

**Issue by Kyblitz** [WorldCretornica/PlotMe-Core#46]
When I try to do /plotme for commands, I get an internal server error. When I try to claim a plot, it says it is not a plotworld, even though it is defined as one in both of the configs.
![2014-12-26_22 00 59](https://cloud.githubusercontent.com/assets/8618899/5560578/248f4d0e-8d4b-11e4-92a2-c7aaf88ae501.png)
![2014-12-26_22 01 13](https://cloud.githubusercontent.com/assets/8618899/5560579/258c42ca-8d4b-11e4-8024-4e6c9f41abc5.png)

**Comment by MattBDev** [comment]
is this fixed in 0.15.2 ? Please let me know so I can close this issue

**Comment by MattBDev** [comment]
No reply so issue is closed
