### ISSUE TITLE
No Plotme Commands

### ISSUE THREAD

**Issue by denniso08** [WorldCretornica/PlotMe-Core#49]
I have no plotme commands at all i do /plotme and all i get is what i put in chat just says /plotme Here is a log of what happens when i boot up.
http://pastebin.com/LzDTrpyX
 
![2014-12-27_10 20 14](https://cloud.githubusercontent.com/assets/10322317/5561039/89529c16-8db2-11e4-8709-24711af0f562.png)

**Comment by MattBDev** [comment]
Is this fixed in 0.15.2 ? Please let me know so I can close this issue

**Comment by MattBDev** [comment]
No reply so issue is closed.
