### ISSUE TITLE
Maven Repository?

### ISSUE THREAD

**Issue by unon1100** [WorldCretornica/PlotMe-Core#50]
Is there a repository that hosts the plotme plugins right now? It would be good to have them, especially being that the one on the hawkfalcon repository doesn't have the API.

**Comment by unon1100** [comment]
Any update on this?

**Comment by MattBDev** [comment]
I still need to contact zachbora about this. I would recommend just setting the dependency locally because I cannot guarantee that the repository version would be compatible with the current version

**Comment by MattBDev** [comment]
There is no repo version for 0.15.2 but I will make sure after 0.16 there will be.
