### ISSUE TITLE
WorldEdit support for plotme move

### ISSUE THREAD

**Issue by EvilOlaf** [WorldCretornica/PlotMe-Core#53]
As already in IRC suggested (not by me) there should be WE used to move plots

Related to https://github.com/WorldCretornica/PlotMe-Core/issues/43

My suggestions in this case:
Do not set WorldEdit as hard dependency. Just disable plot moving when no (supported version of) worldedit has been found and send an error message to the user.

Also I highly recommend to add support for AsyncWorldEdit (just in case if it is need to build in at all, because AWE hooks into WE already), because on hugh plots there would be a lag of death at moving.

Here also I suggest to make a soft dependency on AWE and give out a warning to the user that there WILL be lags if AWE is not found/installed.

**Comment by MattBDev** [comment]
@ZachBora has stated he will be fixing any and all issues with the move command instead of using worldedit.
