### ISSUE TITLE
Support for Citizens Plugin

### ISSUE THREAD

**Issue by MattBDev** [WorldCretornica/PlotMe-Core#6]
Add support for Citizens Plugin in PlotMe. 
http://wiki.citizensnpcs.co/Citizens_Wiki

**Comment by MattBDev** [comment]
This issue has been closed. If this expresses interest from many, I will reopen but the priority is extremely low at the moment.

**Comment by mcmonkey4eva** [comment]
+Support for reopening.  Nothing major is needed, just making sure NPCs can be clicked on and all that

**Comment by MarkusAV** [comment]
Adding Citizens support would be awesome.

**Comment by MattBDev** [comment]
Glad to see people are interested. Ticket reopened

**Comment by AnthonyAMC** [comment]
Yay! The citizens devs are extremely supportive. I'm sure they'd help steer you in the right direction if you have trouble figuring out how to ensure that NPCs can be interacted with.

**Comment by MattBDev** [comment]
I'll start looking into it tonight if no other UUID issues come up

**Comment by MattBDev** [comment]
I believe this is now satisfied with commit 3f0b0b3
If it still needs attention, please comment.

**Comment by AnthonyAMC** [comment]
yay!

**Comment by MattBDev** [comment]
:smile: We will have to wait till 0.17 is released to make sure
