### ISSUE TITLE
plot setowner broken

### ISSUE THREAD

**Issue by EvilOlaf** [WorldCretornica/PlotMe-Core#64]
Setting a new owner of a plot which has been owned before by another player with setowner will cause the new owner is unable to build.

To reproduce:
- Let player X claim a plot
- Let player X try if he can build on his plot
- Set player Y as the owner of the plot with /plot setowner
- Let player Y try if he can build here. He should not be able to do so.
- Set player X as owner again
- Player X should be fine.

Workaround:
- Use /plot dispose to mark the plot as unclaimed
- Let player Y claim the plot
- Player Y is now able to build on this plot.

There is no exceptional output neither ingame nor in console. /plot info shows always the correct owner.
PlotMe 0.15.2 @ Spigot. build from 31.12.

**Comment by SomewhatDisoriented** [comment]
This was fixed by #79 :)

**Comment by MattBDev** [comment]
@SomewhatDisoriented Thanks a bunch for the help :smile:
