### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by Svenlennox** [WorldCretornica/PlotMe-Core#73]
I did /mangaddp A plotme.use but when I want to do /plotme auto it says Permission Denied

**Comment by Svenlennox** [comment]
http://pastebin.com/YM96Cxxj

This is my console log

**Comment by MattBDev** [comment]
I am not sure what /mangaddp is....

**Comment by Svenlennox** [comment]
Its from GroupManager to add permissions

**Comment by MattBDev** [comment]
Well the console log didnt help me much but it looks like you are running 1.8 plugins on a 1.7 server and they aren't working properly

**Comment by Svenlennox** [comment]
What plugins are for 1.8 and am I running on 1.7?

**Comment by MattBDev** [comment]
Just look at your console. I really shouldn't have to tell you this.

**Comment by Svenlennox** [comment]
Citizens and Tab arent working, I know that. but is that hiding the PlotMe plugin?

**Comment by MattBDev** [comment]
I can't tell. you didnt give me a full log.

**Comment by Svenlennox** [comment]
That is the full log?

**Comment by MattBDev** [comment]
That was not the full log. it clearly cut off. look at your link.

**Comment by LukeHandle** [comment]
Hey @Svenlennox, if you stop and start your server, a full log will appear in `[ServerFolder]/logs/latest.log`.
(It is worth mentioning that by default that file will reset at midnight each day and after each server start)

If you then upload that file to pastebin, we might be able to help you with your issues. I won't say for sure, but they sounds permission related and possibly outside the scope of the PlotMe issue tracker...

**Comment by Svenlennox** [comment]
Okay, I used that
http://pastebin.com/3Yj7aTk3

**Comment by LukeHandle** [comment]
Can you also post your PlotMe/Generator configs please.

**Comment by LukeHandle** [comment]
PlotMe loads fine. Can you confirm that as an OP you can do the command?
