### ISSUE TITLE
0.15.2 This is not a plotworld Error

### ISSUE THREAD

**Issue by termitespit** [WorldCretornica/PlotMe-Core#74]
I have PlotMe 0.15.2 and created a world using /mv create plotworld normal -g PlotMe-DefaultGenerator.
When I teleported to the plotworld and did /plotme claim, it said "This is not a plotworld".

**Comment by EvilOlaf** [comment]
Make sure that your plot world is correctly entered in your plotme configuration. Also you need to restart your server in order so plotme can recognize your new plot world. 
No further information provided like logs, config files, running api. 


Therefore invalid
