### ISSUE TITLE
ur plugin is breaked

### ISSUE THREAD

**Issue by vakkq** [WorldCretornica/PlotMe-Core#75]
if i type /plotme or /p i get /plotme as an answer in chat
i use bukkit/spigot 1.7.10
latest ver of plugin
hosthorde hosting with multicraft panel.

pleez h3lp
![mc1710gifcomplete](https://cloud.githubusercontent.com/assets/10379697/5602106/c1ac4622-9337-11e4-9f81-2b3801d85417.gif)

**Comment by EvilOlaf** [comment]
Known issue, related to misconfiguration.  Check your logs and the other issue reports with the same problem.

**Comment by vakkq** [comment]
where r the logs
what do i do
im an idiot plees tell me step by step what do i do
idk where the logs at

**Comment by MarkusAV** [comment]
Pastebin your configurations and error logs for us please
