### ISSUE TITLE
Help with setup

### ISSUE THREAD

**Issue by vakkq** [WorldCretornica/PlotMe-Core#77]
03.01 10:10:54 [Server] ERROR Error occurred while enabling PlotMe v0.15.2 (Is it up to date?)
03.01 10:10:54 [Server] ERROR Is that a mistake? Try making sure you setup PlotMe Correctly PlotMe to stay safe.
03.01 10:10:54 [Server] ERROR Uh oh. There are no plotworlds setup.
03.01 10:10:54 [Server] ERROR The default generator can be downloaded from 
03.01 10:10:54 [Server] ERROR Please ensure that plotworld is set up and that it is using a PlotMe generator
03.01 10:10:54 [Server] ERROR The world plotworld either does not exist or not using a PlotMe generator
03.01 10:10:54 [Server] INFO Enabling PlotMe v0.15.2

**Comment by vakkq** [comment]
Please help i tried:
- Reinstalling Plotme
- Deleting and Re-Generating Plotworld
- Switching from 1.7.10 bukkit to 1.7.9 spigot

**Comment by MarkusAV** [comment]
Read your log.
It says you do not have a plotworld setup, pastebin your configs and full error log thank you.
Also, PlotMe is built for Spigot 1.8
If you have problems setting up PlotMe, read this http://worldcretornica.github.io/PlotMe-Core/setup.html
