### ISSUE TITLE
Plotme Mobs spawning

### ISSUE THREAD

**Issue by Durklas** [WorldCretornica/PlotMe-Core#78]
How to allow mobs to spawn from monsters box???

**Comment by MattBDev** [comment]
Uhhh.... are you in the right place? I am not sure what a "Monsters box" is.

**Comment by Durklas** [comment]
Hmm, Its Id in minecraft 52

**Comment by MattBDev** [comment]
Oh, you mean a mob spawner. Are they not working on plots? On roads they might not work at all. I am not sure what your exact issue is and I can't help you because you didn't explain anything to me.

**Comment by Durklas** [comment]
When I put a mob spawner in my plot, mobs dont spawn from it, If i put it
In survival world they do spawn...My question is How to turn on mob
spawning in plotme?
P.S Srry for my englishn.

**Comment by EvilOlaf** [comment]
Maybe that problem is not related to plotme. Did you set monsters on  multiverse on false or set in world guard mob-spawning to deny? 

Could not test myself yet.

**Comment by Durklas** [comment]
I changed the difficulty from peaceful to hard maybe this will solve the
problem.

**Comment by MarkusAV** [comment]
PlotMe doesn't deny creature spawning. Check other plugins such as multiverse, multiworld, Essentials, worldguard..,
