### ISSUE TITLE
Having trouble when PlotMe starts up

### ISSUE THREAD

**Issue by josephflan** [WorldCretornica/PlotMe-Core#80]
I'm having a issue when PlotMe Core loads. The DefaultGenerator seems to work fine. I have put the error into a pastebin link below.

http://pastebin.com/PaJwBFge

**Comment by josephflan** [comment]
Managed to identify the problem myself. There was config setup for a plotworld that wasnt generated yet. It would cause PlotMe core to 'spaz out' and not load.

**Comment by josephflan** [comment]
Doing the same again now. Seems to be exactly the same error again.

**Comment by MarkusAV** [comment]
These may fix your problem:
* Update WorldEdit to 6.x
* Remember to write your plotworld in all lowercase in the config
* PlotMe 0.15 works best on Minecraft 1.8 Spigot/Craftbukkit
* Offline servers are not supported
