### ISSUE TITLE
Error creating plot world

### ISSUE THREAD

**Issue by EvilOlaf** [WorldCretornica/PlotMe-Core#82]
I know that title is pretty common, but this time I have an other and more ugly error.
Afair generation worked with 0.15.0.

http://pastebin.com/DjFR1wJf

PlotMe 0.15.2 @Spigot 1.8, build from 31.12.

**Comment by MattBDev** [comment]
This is most likely because it couldn't find a world by that name in your generator config. I should add a check for that and have that default to the normal settings. 
Let me know if this helped you

**Comment by EvilOlaf** [comment]
Yes, that worked. I needed a restart till PlotMe-DefaultGenerator recognized the changes in the config file but it worked.
I think creating the world just with default settings is a pretty good idea.

How about this: If someone tries to create a new plot world with a name which is unknown in the config file the world will NOT be generated but a new entry in the config will be written. A message to the creator appears with the hint to edit the config as he wishes and run the command again to start the real creating process. I think this might be even more user friendly.

**Comment by MattBDev** [comment]
@EvilOlaf unfortunately that is not possible at the present time.

**Comment by EvilOlaf** [comment]
So we've got a possible enhancement for the future :D
