### ISSUE TITLE
/p list player not working

### ISSUE THREAD

**Issue by Bobcat00** [WorldCretornica/PlotMe-Core#84]
PlotMe 0.15.2, CraftBukkit version git-Bukkit-53fc3cf (MC: 1.8)
If I issue the command:

/p list playername

I get the following output:

List of plots where playername can build
World:plotworld

But no plots are listed.  I do get a list of my plots if I use my name or leave off the playername.

**Comment by MarkusAV** [comment]
You need to specify the full playername.
Offline servers are not supported by the way.

**Comment by Bobcat00** [comment]
The server is online and I did specify the full player name.

**Comment by MattBDev** [comment]
I can't reproduce. Please update this ticket if the issue still exists.

**Comment by Bobcat00** [comment]
Still seeing the problem.  Here's an example.  I did the following commands:
/p info
/p list LanaPug
/p list lanapug
I thought it was interesting that the command results in two different outputs depending on the case of the player's name.  Server is online.

![plotme_bug](https://cloud.githubusercontent.com/assets/3617206/5884456/b433c728-a32b-11e4-92e3-2d5205a418c2.png)
