### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by Kryptonix2Shot** [WorldCretornica/PlotMe-Core#85]
I have a plotworld created but when ever I try to use the /plotme command it only shows a white message in chat saying /plotme.

Spigot Version: git-Spigot-3ffce45 (1.8-R0.1-SNAPSHOT)

Here is a picture of the message along with the console error on startup
![asd](https://cloud.githubusercontent.com/assets/10392950/5607678/852b58ba-9421-11e4-84fd-5e8b4ab5de71.PNG)
![console](https://cloud.githubusercontent.com/assets/10392950/5607680/8af75ff0-9421-11e4-8bcc-03cfea24d3e6.PNG)

**Comment by MattBDev** [comment]
You are not using the right version of WorldEdit. Also, try opping yourself and using a command. If you can't execute a command while opped you have a serious issue.
