### ISSUE TITLE
How do i create a plotme world WITHOUT multiverse-core.

### ISSUE THREAD

**Issue by UpHeldNetwork** [WorldCretornica/PlotMe-Core#86]
I would really appreciate it if someone could please tell me how to create a plot world WITHOUT using multiverse-core. Thank you in advance.

**Comment by MattBDev** [comment]
This is in the instructions and this is not really a bug. Please do not post here unless you have a bug to report.

**Comment by MattBDev** [comment]
http://worldcretornica.github.io/PlotMe-Core/setup.html
