### ISSUE TITLE
Metadata lock

### ISSUE THREAD

**Issue by MegaNarwhal** [WorldCretornica/PlotMe-Core#88]
Upon trying to optimize my MySQL tables with ```mysqlcheck --optimize -A```, all other plugins have no issue but PlotMe hangs. ```mysqladmin processlist``` reveals that it's stuck at waiting for a table metadata lock on the plotmeAllowed table. Only a minor annoyance but I thought I should report it.

**Comment by MattBDev** [comment]
I don't know much about MySQL but I will look into this.
