### ISSUE TITLE
Someone please help, I'm having an issue installing plotme.

### ISSUE THREAD

**Issue by LegitRedStoner** [WorldCretornica/PlotMe-Core#92]
Someone please help, I'm having an issue installing plotme.

http://gyazo.com/431bafe072f94a2f1d080d750c6f371d

**Comment by MattBDev** [comment]
You need worldedit 6.

**Comment by LegitRedStoner** [comment]
ty

**Comment by LegitRedStoner** [comment]
Would you consider posting that on the plotme download page? it doesn't say it anywhere.

**Comment by MattBDev** [comment]
I have pushed a minor update that warns users and fixes this error from appearing.
