### ISSUE TITLE
"You are not allowed to press buttons on roads" in a non-plot world.

### ISSUE THREAD

**Issue by Foorack** [WorldCretornica/PlotMe-Core#96]
I think the title explains it all. We are running latest version of both plotme and spigot.
We have one plot world and one non-plot world.

I have no idea what information I should post so just tell me and I will do my best. ;)

Kindly Regards
Foorack

TBE

**Comment by MarkusAV** [comment]
Let me just ask you exactly what the issue was.., When you are in your non-plotworld world and press a button it returns "You are not allowed to press buttons on roads"?
I got some questions you could answer as well; WorldEdit version? Offline/online mode? Errors in console?

**Comment by MattBDev** [comment]
There is no message for that or something similar to that in the default captions. Please provide specific version number.

**Comment by Foorack** [comment]
This issue can be deleted as "iccorectly" or "issue not exisiting".

The issue does still exist but the cause of it was not plotme.
The server I was helping have a custom written plugin called "PlotMeAddon" which was the source of the bug, (I had not been informed of this)...

Sorry for taking up your time.

Regards, Foorack.
