### ISSUE TITLE
Plot Trust and Plot Add

### ISSUE THREAD

**Issue by SecretlyJealous** [WorldCretornica/PlotMe-Core#97]
/Plot Add <username> - Players can only build on the owners plot when the plot owner is online.
/Plot Trust <username> - Players trusted on a plot can build even when the plot owner is offline.

**Comment by MattBDev** [comment]
If the player is added to the plot, would they be able to build on it when the user is offline?
If not, it seems dumb to have to give them building access to the plot twice

**Comment by SecretlyJealous** [comment]
If a player is not added to a plot but only trusted to a plot they should be able to build on it even when the owner is offline. This feature would be great because it prevents a lot of greifing.

**Comment by cindyker** [comment]
I saw a server that updated PlotMe to do this. They added a second list for Trusted.
They changed Added, to only allow building if the user is online and made Trusted working like added used to, where you can build anytime.

Players on my server run role playing on their plots and add everyone to it. Then they log off and get griefed. Its actually an annoying problem. 

I would go as far as to hope it had two different economy costs too. 
As I would set Add to a low amount and Trusted to a much higher cost to prevent them from using it a lot.

**Comment by MattBDev** [comment]
This issue is still open because it is something that is planned. Something similar to this will be added but not exactly as described.

**Comment by MattBDev** [comment]
I am adding this to 0.17 and it will work as follows:
- All players that are currently allowed on plots will be allowed to build at any time. (To make it easy to upgrade)
- In the plot allowed table where allowed player data is stored, there will be a column that says trusted and it will be set to true by default.
- the trusted column is a boolean and is set to true if you can build at any time and false if you can only build if the player is online

**Comment by MattBDev** [comment]
I am actually going to switch the name of the column to be "offlineOnly" and the default will be false.

**Comment by MattBDev** [comment]
Added. I just need to finish bug fixes in the implementation.
