### ISSUE TITLE
PlotMe cannot recognize world/not a plot world

### ISSUE THREAD

**Issue by ATon2** [WorldCretornica/PlotMe-Core#98]
Hello,

For some strange reason when two out of my five or so worlds do not recognize as a plotworld upon startup. They have the same config and are using PlotMe-DefaultGenerator as their generator in multiverse-core.

Server Log: http://pastebin.com/QPYs7sJB
PlotMe Config: http://pastebin.com/9K3U5yEU
PlotMe Generator Config: http://pastebin.com/nm8yrRiP
Multiverse Worlds Config: http://pastebin.com/3FYwdzvN

Please help, thank you.

- ATon2

**Comment by MattBDev** [comment]
Try reloading the server. if it still does not like them, try to add the generator in the bukkit.yml file and see if it works. If none of that works. let me know because I think that this may be a valid issue.

**Comment by ATon2** [comment]
None of that seemed to work.

**Comment by MattBDev** [comment]
Thanks for this report. I will be trying my hardest to fix this.

**Comment by MarkusAV** [comment]
Not that I think it would do anything, but why do you have a double "PathWidth" property in the defaultgenerator settings?

**Comment by ATon2** [comment]
Ahh that must be from when I attempted to copy and paste the world Config from a working plot world to the broken ones. Regardless, the worlds that are broken are plotworld and rankworld. Rankworld does not have the double path width yet is still broken.

**Comment by MattBDev** [comment]
I will try to fix the issue. It is due to some messy code that can be written more efficiently.

**Comment by MarkusAV** [comment]
Closing this, you might want to add it to the 0.16 milestone?

**Comment by MattBDev** [comment]
Please try Renaming the worlds to lowercase (everywhere) if they are not already, the generator is case-sensitive in the config for some reason so make sure it is okay there, add the generator to the bukkit.yml and let me know if any of this works. provide me a bukkit.yml and plotme configs if this doesn't work. .

**Comment by ATon2** [comment]
They are already lowercase.

**Comment by MattBDev** [comment]
You didn't add the generator properly to the bukkit.yml
Follow the http://wiki.bukkit.org/Bukkit.yml#.2AOPTIONAL.2A_worlds

**Comment by ATon2** [comment]
That seemed to work, thank you!
It's still strange it doesn't work with multiverse though.
