### ISSUE TITLE
Plot world with PlotMe Generator

### ISSUE THREAD

**Issue by gustebeast** [WorldCretornica/PlotMe-Core#99]
I have a freebuild world which I keep part plotme part regular creative. Basically I have a large square in the center of the map filled with plots, then outside that square I have regular map. I did this by first generating using plotme, then switching back to the normal generator. With the old plot me, this wasnt a problem (I gave the players I wanted to be able to build outside the box permission to override plots), but now it says that the world isnt a plot world.

Ideal:
Have a way to set the max dimensions to generate plots so other people can do this duel freebuild world style. (then you could even have a plotme area within a regular world)

Realistic:
Dont disable support on a world just because its generator is the normal one. The plots are all in the database and should be able to load normally. In other words, if the world is already generated the plugin should just pretend everything is a plot no matter what it actually looks like.

**Comment by MattBDev** [comment]
Support is disabled if the generator is not built upon the PlotMe-AbstractGenerator. This is how clearing, generating, and plot boundaries are detected. Unless someone builds a generator that allows for a normal world type of generation, this in't possible.

**Comment by MattBDev** [comment]
The generator was separated so lots of different plotworld generation possibilities can be made. That was a big limitation on the previous generator. Doing what you ask would require a lot of "hacky" type of code and require depending on CraftBukkit instead of bukkit, which causes compatibility issues.
